"use client";
import {useState} from 'react';
import {useRuntime,entityRef} from '../../core/runtime-context';
import {Action,Field} from '../../core/runtime-panels';
import {text,type Entity} from '../live/types';
export function downloadCalendar(title:string,start:string){
 const escape=(v:string)=>v.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;'),date=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d+Z$/,'Z');
 const from=new Date(start),to=new Date(from.getTime()+30*60000);
 const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Elfred//Local Calendar//ZH','BEGIN:VEVENT',`UID:${crypto.randomUUID()}@elfred.local`,`DTSTAMP:${date(new Date())}`,`DTSTART:${date(from)}`,`DTEND:${date(to)}`,`SUMMARY:${escape(title)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');
 const url=URL.createObjectURL(new Blob([body],{type:'text/calendar;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='elfred-event.ics';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function GroupRecords({conversation}:{conversation:Entity}){
 const runtime=useRuntime()!,snapshot=runtime.snapshot!;
 const [title,setTitle]=useState(''),[content,setContent]=useState(''),[kind,setKind]=useState('conclusion'),[editing,setEditing]=useState<Entity|null>(null),[sources,setSources]=useState<string[]>([]),[goal,setGoal]=useState(''),[recordAssignee,setRecordAssignee]=useState(snapshot.user.id),[assignee,setAssignee]=useState(''),[due,setDue]=useState('');
 if(conversation.data.kind!=='group')return null;
 const records=snapshot.objects.shared_record.filter(item=>item.space===conversation.id&&['active','proposed'].includes(text(item,'status')));
 return <section className="v277-edit-card"><h3>群共享记录</h3><p>由真人确认的目标、结论、分歧和简报，所有当前群成员可查看。</p>{records.map(item=><article key={item.id}><b>{text(item,'title')}</b><p style={{whiteSpace:'pre-wrap'}}>{text(item,'content')}</p><small>v{item.version} · {item.data.status==='proposed'?'候选，待负责人确认':'本人已确认'} · {new Date(item.updated).toLocaleString('zh-CN')}</small>{item.data.status==='proposed'&&item.data.assignee===snapshot.user.id&&<Action run={()=>runtime.command('group.record.confirm',{...entityRef(item),confirm:true})}>确认此目标或结论及其范围</Action>}<details><summary>修改历史与来源</summary>{((item.data.history||[]) as {version:number;content:string}[]).map(h=><p key={h.version}>v{h.version}：{h.content}</p>)}</details>{(item.owner===snapshot.user.id||(conversation.owner===snapshot.user.id&&item.data.kind!=='disagreement'))&&<><button className="v277-secondary" onClick={()=>{setEditing(item);setTitle(text(item,'title'));setContent(text(item,'content'));setKind(text(item,'kind'));setRecordAssignee(text(item,'assignee')||snapshot.user.id);setSources(((item.data.source_refs||[]) as {id:string}[]).map(ref=>ref.id))}}>编辑记录</button><Action run={()=>runtime.command('group.record.archive',entityRef(item))}>归档记录</Action></>}</article>)}<details open={editing?true:undefined}><summary>{editing?'编辑共享记录':'新增共享记录'}</summary><label className="v277-field"><span>类型</span><select value={kind} onChange={e=>setKind(e.target.value)}>{[['goal','共同目标'],['conclusion','候选结论'],['disagreement','待解决分歧'],['brief','群简报'],['calendar','日程候选'],['minutes','共享纪要']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{['goal','conclusion'].includes(kind)&&<label className="v277-field">确认此项的负责人<select value={recordAssignee} onChange={e=>setRecordAssignee(e.target.value)}>{conversation.members?.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}<Field name="记录标题" value={title} onChange={setTitle}/><Field name="确认公开到群的内容" value={content} onChange={setContent} area/><details><summary>选择群消息依据</summary>{snapshot.objects.message.filter(m=>m.space===conversation.id).map(m=><label key={m.id} style={{display:'block'}}><input type="checkbox" checked={sources.includes(m.id)} onChange={e=>setSources(old=>e.target.checked?[...old,m.id]:old.filter(id=>id!==m.id))}/>{text(m,'sender_name')}：{text(m,'text').slice(0,100)}</label>)}</details><Action disabled={!title.trim()||!content.trim()} run={async()=>{await runtime.command('group.record.save',{...(editing?entityRef(editing):{}),conversation_id:conversation.id,title,content,kind,assignee:recordAssignee,source_refs:snapshot.objects.message.filter(m=>sources.includes(m.id)).map(entityRef)});setEditing(null);setTitle('');setContent('');setSources([])}}>确认保存到群共享记录</Action>{editing&&<button className="v277-secondary" onClick={()=>{setEditing(null);setTitle('');setContent('');setSources([])}}>取消编辑</button>}</details>
 <details><summary>提议一个待负责人确认的事项</summary><Field name="候选事项" value={goal} onChange={setGoal} area/><label className="v277-field"><span>负责人</span><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">尚未指定，保留候选</option>{conversation.members?.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><Field name="截止时间" type="datetime-local" value={due} onChange={setDue}/><Action disabled={!goal.trim()} run={async()=>{await runtime.command('commitment.create',{conversation_id:conversation.id,goal,assignee,due:due?new Date(due).toISOString():null});setGoal('')}}>提议，由负责人本人接受</Action></details>
 {snapshot.objects.commitment.filter(item=>item.space===conversation.id).map(item=><CommitmentChanges key={item.id} item={item}/>)}
 </section>;
}
function CommitmentChanges({item}:{item:Entity}){
 const runtime=useRuntime()!,[nextAssignee,setNextAssignee]=useState(''),[editing,setEditing]=useState(false),[goal,setGoal]=useState(text(item,'goal')),[due,setDue]=useState(''),[baseVersion,setBaseVersion]=useState(item.version);
 const canChange=item.owner===runtime.snapshot!.user.id||item.data.assignee===runtime.snapshot!.user.id;
 const conversation=runtime.snapshot!.objects.conversation.find(c=>c.id===item.space);
 return <article><p>{text(item,'goal')}{item.data.due?` · 截止 ${new Date(text(item,'due')).toLocaleString('zh-CN')}`:''}</p>{!item.data.assignee&&item.data.status!=='withdrawn'&&<><p>未指定负责人 · 尚未成为任何人的承诺</p>{(item.owner===runtime.snapshot!.user.id||(conversation?.owner===runtime.snapshot!.user.id&&!conversation.members?.some(m=>m.id===item.owner)))&&<><select aria-label="候选负责人" value={nextAssignee} onChange={e=>setNextAssignee(e.target.value)}><option value="">选择当前成员</option>{conversation?.members?.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><Action disabled={!nextAssignee} run={()=>runtime.command('commitment.assign',{...entityRef(item),assignee:nextAssignee})}>提出负责人，等待本人接受</Action></>}</>}{item.data.status==='proposed'&&item.data.assignee===runtime.snapshot!.user.id&&<><Action run={()=>runtime.command('commitment.respond',{...entityRef(item),accept:true})}>接受为本人任务草稿</Action><Action run={()=>runtime.command('commitment.respond',{...entityRef(item),accept:false})}>拒绝</Action></>}{Boolean(item.data.due)&&<button className="v277-secondary" onClick={()=>downloadCalendar(text(item,'goal'),text(item,'due'))}>下载日历提醒</button>}{canChange&&item.data.status!=='withdrawn'&&<><button className="v277-secondary" onClick={()=>{setGoal(text(item,'goal'));setBaseVersion(item.version);setDue(item.data.due?new Date(Date.parse(text(item,'due'))-new Date(text(item,'due')).getTimezoneOffset()*60000).toISOString().slice(0,16):'');setEditing(true)}}>修改事项与截止日期</button><Action run={()=>runtime.command('commitment.withdraw',entityRef(item))}>撤回此事项</Action></>}{editing&&<><Field name="修改后的事项" value={goal} onChange={setGoal}/><Field name="截止日期" type="datetime-local" value={due} onChange={setDue}/><p>修改后需负责人重新接受。本人再次接受后更新原任务，保留其历史和进度；正在运行的任务需先停止。</p><Action disabled={!goal.trim()} run={async()=>{await runtime.command('commitment.revise',{id:item.id,version:baseVersion,goal,due:due?new Date(due).toISOString():null});setEditing(false)}}>提交修改并等待重新确认</Action></>}</article>;
}
