"use client";
import {AtSign,ChevronRight,FileText,Layers3,Orbit,Sparkles} from 'lucide-react';
import {useRuntime} from '../../core/runtime-context';
import {text,type Entity} from '../live/types';
export function MentionPicker({query,busy,onPersonal,onResource,onDismiss}:{query:string;busy:boolean;onPersonal:()=>void;onResource:(item:Entity)=>void;onDismiss:()=>void}){
 const runtime=useRuntime()!,snapshot=runtime.snapshot!,keyword=query.trim().toLocaleLowerCase();
 const resources=keyword?[...snapshot.objects.skill,...snapshot.objects.document,...snapshot.objects.knowledge,...snapshot.objects.resource].filter(item=>!['archived','deleted','rejected','superseded','expired','needs_review'].includes(text(item,'status'))&&[text(item,'title'),text(item,'name'),text(item,'instructions')].join(' ').toLocaleLowerCase().includes(keyword)).slice(0,6):[];
 return <section id="elfred-mention-picker" className="elfred-mention-picker" aria-label="调用" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();onDismiss()}}}><p className="elfred-mention-title">调用</p><div className="elfred-mention-card"><button type="button" className="elfred-mention-personal" disabled={busy} onMouseDown={event=>event.preventDefault()} onClick={onPersonal}><span className="elfred-mention-logo"><Orbit size={30} strokeWidth={1.5}/></span><span className="elfred-mention-identity"><strong>我的 Elfred</strong><small>Personal Agent · 仅调用我的能力</small></span><ChevronRight className="elfred-mention-chevron" size={21}/></button>{keyword&&<div className="elfred-mention-results">{resources.length?resources.map(item=><button type="button" key={item.id} disabled={busy} onMouseDown={event=>event.preventDefault()} onClick={()=>onResource(item)}>{item.type==='skill'?<Layers3 size={19}/>:<FileText size={19}/>}<span><strong>{text(item,'title')||text(item,'name')}</strong><small>{item.type==='skill'?(text(item,'kind')||'Skill'):'我的资料'}</small></span><ChevronRight size={17}/></button>):<p>没有匹配的插件、文件或技能</p>}</div>}<div className="elfred-mention-hint"><span><AtSign size={20}/><Sparkles size={9}/></span><p>继续输入，以搜索插件、文件、文件夹和技能</p></div></div></section>;
}
