"use client";
import {Card,Empty,Badge,Action,Form,Content} from './ui';
import {text,ref,type Snapshot,type Command} from './types';
export function CommunityView({snapshot,command,selected,select}:{snapshot:Snapshot;command:Command;selected:string|null;select:(id:string|null)=>void}){
  const objects=snapshot.objects,project=objects.project.find(item=>item.id===selected);
  if(project)return <><Action secondary onClick={()=>select(null)}>返回社区</Action><Card><Badge value={text(project,'status')}/><h2>{text(project,'title')}</h2><p>{text(project,'goal')}</p><small>验收：{text(project,'criteria')} · 工作版本 {String(project.data.revision)}</small><p>开放任务：{text(project,'task')}</p><small>当前成员：{project.members?.map(member=>member.name).join('、')}</small>{project.owner===snapshot.user.id&&<Form fields={[{name:'confirm',label:'已核对目标、开放任务及公开范围',type:'checkbox',required:true}]} submit="确认发布招募帖" onSubmit={async()=>command('project.publish_post',{...ref(project),confirm:true})}/>}</Card>
    <Card><h3>我的独立工作副本</h3><p>每位成员独立创作，本人检查后提交，发起者采纳后才能发布。</p><Action onClick={()=>command('copy.create',{project_id:project.id})}>从当前版本创建副本</Action>{objects.copy.filter(item=>item.data.project_id===project.id).map(copy=><Card key={copy.id}><small>基于版本 {String(copy.data.base_revision)}</small><Badge value={text(copy,'status')}/>{text(copy,'status')==='draft'?<><Form fields={[{name:'content',label:'本人成果',type:'textarea',value:text(copy,'content')}]} submit="保存工作副本" onSubmit={async values=>command('copy.save',{...ref(copy),content:values.content})}/><Form fields={[{name:'reviewed',label:'我已检查此副本内容，同意提交给项目成员',type:'checkbox',required:true}]} submit="提交贡献" onSubmit={async()=>command('copy.submit',{...ref(copy),reviewed:true})}/></>:<Content value={copy.data.content}/>}</Card>)}</Card>
    <Card><h3>阶段反馈</h3><Form fields={[{name:'kind',label:'反馈类型',type:'select',options:[{value:'progress',label:'进展'},{value:'blocked',label:'阻塞'},{value:'dependency',label:'依赖变化'}]},{name:'content',label:'与项目有关的反馈',type:'textarea'}]} submit="分享阶段反馈" onSubmit={async values=>command('project.feedback',{...values,id:project.id})}/>{objects.feedback.filter(item=>item.space===project.id).map(item=><p key={item.id}>{text(item,'content')}</p>)}</Card>
    <h3>贡献与审查</h3>{objects.contribution.filter(item=>item.data.project_id===project.id).map(item=><Card key={item.id}><Badge value={text(item,'status')}/><small>基于版本 {String(item.data.base_revision)}</small><Content value={item.data.content}/>{item.data.feedback?<p>{text(item,'feedback')}</p>:null}{project.owner===snapshot.user.id&&text(item,'status')==='submitted'&&<Form fields={[{name:'decision',label:'审查决定',type:'select',options:[{value:'accept',label:'采纳'},{value:'changes',label:'请修改'},{value:'reject',label:'拒绝'}]},{name:'feedback',label:'审查反馈',required:false}]} submit="提交审查决定" onSubmit={async values=>command('contribution.review',{...ref(item),...values})}/>}</Card>)}
    {project.owner===snapshot.user.id&&<Card><h3>发布静态成果</h3><p>发布者检查采纳内容后确认。所有内容按纯文本展示，代码不会在页面执行。</p><Form fields={[{name:'confirm',label:'我已核对成果及公开范围，确认发布',type:'checkbox',required:true},{name:'allow_fork',label:'允许他人保留来源后复制再创作',type:'checkbox'},{name:'tool_description',label:'工具与 AI 协作说明',type:'textarea'}]} submit="确认发布成果" onSubmit={async values=>command('project.release',{...ref(project),confirm:true,allow_fork:values.allow_fork==='on',tool_description:values.tool_description})}/></Card>}
    {objects.release.filter(item=>item.data.project_id===project.id).map(item=><Card key={item.id}><h3>发布版本 {String(item.data.revision)} {project.data.release_id===item.id?'· 当前':''}</h3><Content value={item.data.content}/>{project.owner===snapshot.user.id&&project.data.release_id!==item.id&&<Action secondary onClick={()=>command('project.rollback',{...ref(project),release_id:item.id})}>恢复这个发布版本</Action>}</Card>)}
    {project.owner===snapshot.user.id&&<details className="live-card"><summary>项目成员管理</summary>{project.members?.filter(member=>member.id!==project.owner).map(member=><p key={member.id}>{member.name}<Action secondary onClick={()=>command('project.remove_member',{...ref(project),user_id:member.id})}>撤销项目成员资格</Action></p>)}</details>}</>;
  return <><div className="live-section-title"><h2>一起把想法做出来</h2><small>真人发起 · 各自创作</small></div><details className="live-card"><summary>发起共创项目</summary><Form fields={[{name:'title',label:'项目名'},{name:'goal',label:'想共同完成什么',type:'textarea'},{name:'task',label:'第一项开放任务'},{name:'criteria',label:'验收标准'},{name:'participation',label:'参与方式',type:'select',options:[{value:'open',label:'普通任务，确认后认领'},{value:'application',label:'受限任务，需要发起者批准'}]}]} submit="创建私有项目草稿" onSubmit={async values=>{const result=await command('project.create',values);if(result)select(result.id)}}/></details>
    {objects.project.length>0&&<Card><h3>我参与的项目</h3>{objects.project.map(item=><button className="live-item" key={item.id} onClick={()=>select(item.id)}>{text(item,'title')}<Badge value={text(item,'status')}/></button>)}</Card>}
    {objects.post.length===0&&<Empty>尚无公开共创帖。项目草稿需要本人确认后才会出现在这里。</Empty>}{objects.post.map(item=><Card key={item.id}><Badge value={text(item,'status')}/><h2>{text(item,'title')}</h2><p>{text(item,'content')}</p><small>开放任务：{text(item,'task')}</small><div className="live-actions">{objects.project.some(project=>project.id===item.data.project_id)?<Action onClick={()=>select(text(item,'project_id'))}>进入项目</Action>:<Action onClick={async()=>{const result=await command('project.claim',{post_id:item.id,confirm:true});if(result?.project_id&&text(item,'participation')==='open')select(result.project_id)}}>{text(item,'participation')==='open'?'确认参与并认领':'申请参与'}</Action>}{[['like','喜欢'],['save','收藏'],['report','举报']].map(([kind,label])=><Action secondary key={kind} onClick={()=>command('post.interact',{id:item.id,kind})}>{label}</Action>)}</div></Card>)}
    <h3>已发布作品</h3>{objects.release.map(item=><Card key={item.id}><h3>{text(item,'title')}</h3><Content value={item.data.content}/>{text(item,'license')==='copy-with-attribution'&&<Form fields={[{name:'goal',label:'你的再创作目标'}]} submit="复制并开始独立创作" onSubmit={async values=>{const result=await command('project.fork',{release_id:item.id,goal:values.goal});if(result)select(result.id)}}/>}</Card>)}</>;
}
