"use client";
import {useState} from 'react';
import {Card,Empty,Badge,Item,Action,Form} from './ui';
import {text,ref,type Snapshot,type Command} from './types';
export function KnowledgeView({snapshot,command,openObject}:{snapshot:Snapshot;command:Command;openObject:(id:string)=>Promise<void>}){
  const [tab,setTab]=useState('assets'),[query,setQuery]=useState(''),[uploadError,setUploadError]=useState('');const objects=snapshot.objects;
  return <><div className="live-tabs">{[['assets','资产'],['memory','记忆'],['capability','能力与方法']].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='assets'&&<><Card><h2>保存真实资料</h2><p>支持 UTF-8 文字、Markdown、CSV 与 JSON。解析失败会保留错误提示。</p><label className="live-upload">选择文件<input aria-label="上传资料" type="file" accept=".txt,.md,.csv,.json" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;setUploadError('');if(file.size>500000){setUploadError('文件超过本地 500 KB 限制');return;}try{await command('document.create',{title:file.name,content:await file.text()});}catch{setUploadError('读取文件失败')}}}/></label>{uploadError&&<p role="alert">{uploadError}</p>}<details><summary>直接写一条知识笔记</summary><Form fields={[{name:'title',label:'标题'},{name:'content',label:'内容',type:'textarea'}]} submit="保存笔记" onSubmit={async values=>command('knowledge.create',values)}/></details></Card><label className="live-search">查找资产<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="按标题或内容筛选"/></label>{[...objects.document,...objects.knowledge].filter(item=>`${text(item,'title')} ${text(item,'content')}`.includes(query)).map(item=><Item key={item.id} item={item} onClick={()=>void openObject(item.id)}/>)}{objects.document.length+objects.knowledge.length===0&&<Empty>没有预置成果。上传资料或完成一项真实任务后即可查看。</Empty>}</>}
  {tab==='memory'&&<><p className="live-note">理解按具体条目与证据记录；确认记忆不会扩大权限。</p><Card><Form fields={[{name:'content',label:'希望 Elfred 理解的内容',type:'textarea'},{name:'scope',label:'适用范围',type:'select',options:[{value:'owner',label:'本人全局'},...snapshot.systems.map(item=>({value:item.id,label:item.name}))]},{name:'risk',label:'影响',type:'select',options:[{value:'high',label:'身份、关系、价值观或长期目标（需确认）'},{value:'low',label:'可撤销的工作偏好'}]}]} submit="保存待核对理解" onSubmit={async values=>command('memory.create',values)}/></Card>{objects.memory.map(item=><Card key={item.id}><Badge value={text(item,'status')}/><p>{text(item,'content')}</p><small>范围：{text(item,'scope')} · 理解：<Badge value={text(item,'alignment')}/></small>{!['superseded','rejected','deleted'].includes(text(item,'status'))&&<><div className="live-actions">{[['confirm','确认'],['defer','搁置'],['reject','否认'],['delete','删除']].map(([decision,label])=><Action secondary key={decision} onClick={()=>command('memory.decide',{...ref(item),decision})}>{label}</Action>)}</div><details><summary>修正这条理解</summary><Form fields={[{name:'content',label:'正确的内容',type:'textarea',value:text(item,'content')}]} submit="保存修正并使旧理解失效" onSubmit={async values=>command('memory.decide',{...ref(item),decision:'correct',content:values.content})}/></details></>}</Card>)}</>}
  {tab==='capability'&&<><Card className="live-welcome"><h2>让能力有据可查</h2><p>以实际验收成果为依据，不用任务次数生成等级或能力分。</p><strong>{objects.task.filter(item=>text(item,'status')==='completed').length} 项已验收成果</strong></Card>{objects.knowledge.filter(item=>item.data.kind==='accepted_result').map(item=><Item key={item.id} item={item} onClick={()=>void openObject(item.id)}/>)}<h3>可复用方法</h3>{objects.skill.length===0?<Empty>验收任务后可保存方法草稿；自动改进候选需要独立评测与批准。</Empty>:objects.skill.map(item=><Card key={item.id}><h3>{text(item,'title')}</h3><p>{text(item,'instructions')}</p><Badge value={text(item,'status')}/></Card>)}</>}
  </>;
}
