"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {Home,MessageCircle,Library,UserRound,Compass,Lightbulb,PenLine,Link2,CheckCircle2,ArrowLeft,Search,Plus,RefreshCw,Sparkles,ListTodo,Bell} from 'lucide-react';
import {Card,Empty,Badge,Item,Action,Form,Content} from './ui';
import {text,ref,type Entity,type Snapshot,type User,type Result} from './types';
import {TasksView} from './tasks-view';
import {KnowledgeView} from './knowledge-view';
import {MessagesView} from './messages-view';
import {CommunityView} from './community-view';
import {ProfileView} from './profile-view';
import './live.css';

type Screen='home'|'tasks'|'knowledge'|'messages'|'community'|'profile'|'search'|'agent'|'notifications'|'tools'|'object';
const labels:Record<Screen,string>={home:'Elfred',tasks:'任务中心',knowledge:'知识',messages:'消息',community:'社区',profile:'我的',search:'全局搜索',agent:'本人 Agent',notifications:'通知',tools:'我的工具',object:'来源详情'};
export default function LiveApp(){
  const [user,setUser]=useState<User|null>(null),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[register,setRegister]=useState(false),[screen,setScreen]=useState<Screen>('home'),[selected,setSelected]=useState<string|null>(null),[system,setSystem]=useState('create'),[searchResult,setSearchResult]=useState<{hits:{id:string;title:string;excerpt:string;anchor:string}[]}|null>(null),[object,setObject]=useState<Entity|null>(null);
  const csrf=useRef(''),pending=useRef(new Map<string,string>()),previous=useRef<Screen>('home');
  const api=useCallback(async<T,>(path:string,body?:unknown,key?:string):Promise<T>=>{
    const response=await fetch('/api/elfred'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-Elfred-Client':'1','X-CSRF-Token':csrf.current,...(key?{'Idempotency-Key':key}:{})},body:body===undefined?undefined:JSON.stringify(body)});
    const result=await response.json() as {error?:{message:string}};if(!response.ok)throw new Error(result.error?.message||'服务暂时不可用');return result as T;
  },[]);
  const refresh=useCallback(async()=>{const result=await api('/bootstrap') as Snapshot;setSnapshot(result);setUser(result.user);},[api]);
  useEffect(()=>{let active=true;void api<{user:User|null;csrf:string|null}>('/session').then(async result=>{if(!active)return;csrf.current=result.csrf||'';setUser(result.user);if(result.user)await refresh();}).catch(err=>setError(err.message)).finally(()=>setLoading(false));return()=>{active=false}},[api,refresh]);
  useEffect(()=>{if(!user)return;const timer=setInterval(()=>{void refresh().catch(err=>setError(err.message));},4000);return()=>clearInterval(timer)},[user,refresh]);
  const command=async(action:string,input:Record<string,unknown>):Promise<Result|undefined>=>{
    setError('');const fingerprint=JSON.stringify({action,input});let key=pending.current.get(fingerprint);if(!key){key=crypto.randomUUID();pending.current.set(fingerprint,key)}
    try{const result=await api('/commands',{action,input},key) as Result;pending.current.delete(fingerprint);await refresh();return result;}catch(err){setError(err instanceof Error?err.message:'操作失败，请重试');return undefined}
  };
  const go=(next:Screen,id:string|null=null)=>{previous.current=screen;setScreen(next);setSelected(id);setError('');};
  const openObject=async(id:string)=>{try{const item=await api('/objects/'+encodeURIComponent(id)) as Entity;setObject(item);go('object',id);}catch(err){setError(err instanceof Error?err.message:'来源不可访问')}};
  const objects=(type:string)=>snapshot?.objects[type]||[];
  if(loading)return <main className="live-app live-boot"><Sparkles/><h1>Elfred</h1><p>正在读取你的工作空间…</p></main>;
  if(!user||!snapshot)return <main className="live-app live-login"><div className="live-brand"><Sparkles/><span>ELFRED</span></div><h1>从你的目标开始</h1><p>你的思考、关系与成果，在自己的空间里持续积累。</p>{error&&<div role="alert" className="live-error">{error}</div>}<Card><h2>{register?'创建账号':'欢迎回来'}</h2><Form key={String(register)} fields={[{name:'handle',label:'账号',placeholder:'字母、数字或 _.@-'},...(register?[{name:'name',label:'称呼',required:false}]:[]),{name:'password',label:'密码（10—128 位）',type:'password'}]} submit={register?'创建并进入':'登录'} onSubmit={async values=>{try{setError('');const result=await api<{user:User;csrf:string}>(register?'/auth/register':'/auth/login',{...values,name:values.name||values.handle});csrf.current=result.csrf;setUser(result.user);await refresh();}catch(err){setError(err instanceof Error?err.message:'登录失败')}}}/><Action secondary onClick={()=>setRegister(!register)}>{register?'已有账号，去登录':'没有账号，创建一个'}</Action></Card><small>本机持久空间 · 账号数据独立保存</small></main>;
  const onboarding=objects('onboarding')[0],activeTasks=objects('task').filter(item=>!['completed','cancelled'].includes(text(item,'status')));
  return <main className="live-app"><header className="live-header">{screen!=='home'?<button aria-label="返回" onClick={()=>go(['object','agent','search','tasks','tools','notifications'].includes(screen)?previous.current==='object'?'home':previous.current:'home')}><ArrowLeft size={21}/></button>:<button aria-label="我的工具" onClick={()=>go('tools')}><Sparkles size={22}/></button>}<strong>{labels[screen]}</strong><button aria-label="刷新" onClick={()=>void refresh().catch(err=>setError(err.message))}><RefreshCw size={18}/></button><button aria-label="通知" onClick={()=>go('notifications')}><Bell size={19}/>{objects('notification').some(item=>text(item,'status')==='unread')&&<i/>}</button></header>
    {error&&<div role="alert" className="live-error">{error}<button aria-label="关闭提示" onClick={()=>setError('')}>×</button></div>}
    <div className="live-scroll">
      {screen==='home'&&<><div className="live-tabs"><button className="active">动态</button><button onClick={()=>go('community')}>社区</button><button onClick={()=>go('tasks')}><ListTodo size={17}/>任务 {activeTasks.length||''}</button></div><button className="live-search" onClick={()=>go('search')}><Search size={18}/>搜索资料、消息、任务与成果</button>
      {onboarding&&text(onboarding,'status')!=='completed'&&<Card className="live-welcome"><small>让我们从一件事开始</small><h2>现在，你想完成什么？</h2><Form fields={[{name:'intent',label:'第一个意图',type:'textarea',value:text(onboarding,'intent'),placeholder:'可以是一个问题、一份资料，或一个想法'}]} submit="保存意图，创建任务草稿" onSubmit={async values=>{await command('onboarding.save',{...ref(onboarding),intent:values.intent});const result=await command('task.create',{goal:values.intent,mode:'compose',system:'create'});if(result)go('tasks',result.id)}}/><Action secondary onClick={()=>command('onboarding.complete',{...ref(onboarding),skip:true})}>稍后再说，进入首页</Action></Card>}
      <div className="live-section-title"><h2>今天与你有关</h2><small>根据真实任务</small></div><div className="live-brief-grid">{[['morning','早间','确认重点'],['noon','午间','确认调整'],['evening','晚间','核对结果']].map(([kind,name,hint])=><button key={kind} onClick={async()=>{const result=await command('brief.create',{kind});if(result)void openObject(result.id)}}><small>{name}</small><strong>{hint}</strong><span>{kind==='evening'?objects('task').filter(item=>text(item,'status')==='awaiting_acceptance').length+' 项待验收':activeTasks.length+' 项进行中'}</span></button>)}</div>
      <div className="live-systems">{snapshot.systems.map((item,index)=>{const Icon=[Compass,Lightbulb,PenLine,Link2,CheckCircle2][index];return <button key={item.id} onClick={()=>{setSystem(item.id);go('agent')}}><span><Icon size={22}/></span>{item.name}</button>})}</div>
      <div className="live-section-title"><h2>你的动态</h2><small>成果与值得继续的事</small></div>{objects('feed').length===0?<Empty>完成并验收第一项任务后，真实成果会出现在这里。</Empty>:objects('feed').filter(item=>!objects('interaction').some(interaction=>interaction.data.object_id===item.id&&interaction.data.kind==='hide'&&interaction.data.active)).map(item=><Card key={item.id}><small>{snapshot.systems.find(system=>system.id===item.data.system)?.name} · 成果</small><h3>{text(item,'title')}</h3><p>{text(item,'summary')}</p><div className="live-actions"><Action secondary onClick={()=>go('tasks',text(item,'task_id'))}>查看任务</Action>{['like','save','hide'].map((kind,index)=><Action secondary key={kind} onClick={()=>command('feed.interact',{id:item.id,kind})}>{objects('interaction').some(interaction=>interaction.data.object_id===item.id&&interaction.data.kind===kind&&interaction.data.active)?'取消':''}{['喜欢','收藏','忽略'][index]}</Action>)}<Action secondary onClick={()=>command('inbox.create',{object_id:item.id})}>稍后处理</Action></div></Card>)}</>}
      {(screen==='tasks'||screen==='agent')&&<TasksView snapshot={snapshot} selected={selected} select={setSelected} command={command} system={screen==='agent'?system:undefined} openObject={openObject}/>}
      {screen==='knowledge'&&<KnowledgeView snapshot={snapshot} command={command} openObject={openObject}/>}
      {screen==='messages'&&<MessagesView snapshot={snapshot} command={command} selected={selected} select={setSelected} goTask={id=>go('tasks',id)}/>}
      {screen==='community'&&<CommunityView snapshot={snapshot} command={command} selected={selected} select={setSelected}/>}
      {screen==='profile'&&<ProfileView snapshot={snapshot} command={command} logout={async()=>{await api('/auth/logout',{});csrf.current='';setSnapshot(null);setUser(null);setSelected(null);setScreen('home');pending.current.clear();}}/>}
      {screen==='search'&&<><p className="live-note">默认只搜索你有权访问的应用内资料。私人记忆需在知识页单独查看。</p><Form fields={[{name:'query',label:'搜索词',placeholder:'例如：报名限制'},{name:'type',label:'范围',type:'select',options:[{value:'',label:'全部授权内容'},{value:'document',label:'资料'},{value:'message',label:'消息'},{value:'task',label:'任务'},{value:'knowledge',label:'知识成果'}]}]} submit="搜索" onSubmit={async values=>{try{setError('');setSearchResult(await api<{hits:{id:string;title:string;excerpt:string;anchor:string}[]}>('/search',{query:values.query,...(values.type?{types:[values.type]}:{})}));}catch(err){setError(err instanceof Error?err.message:'搜索失败')}}}/>{searchResult&&<><small>关键词检索 · 语义条件尚未核实 · {searchResult.hits.length} 条</small>{searchResult.hits.length===0&&<Empty>没有匹配内容。可以修改关键词；不会自动放宽条件。</Empty>}{searchResult.hits.map(hit=><Card key={hit.id}><button className="live-link" onClick={()=>void openObject(hit.id)}>{hit.title}</button><p>{hit.excerpt}</p><small>{hit.anchor}</small></Card>)}</>}</>}
      {screen==='notifications'&&<>{objects('notification').length===0&&<Empty>暂无通知。</Empty>}{objects('notification').map(item=><Card key={item.id}><p>{text(item,'summary')}</p><div className="live-actions"><Action secondary onClick={()=>void openObject(text(item,'target_id'))}>查看来源</Action>{text(item,'status')==='unread'&&<Action onClick={()=>command('notification.read',ref(item))}>标记已读</Action>}</div></Card>)}</>}
      {screen==='tools'&&<><h2>固定的方法与待处理</h2>{objects('skill').length===0&&<Empty>验收任务后，可以把可复用方法保存到这里。</Empty>}{objects('skill').map(item=><Card key={item.id}><h3>{text(item,'title')}</h3><p>{text(item,'instructions')}</p><Action secondary onClick={()=>command('shortcut.pin',{skill_id:item.id})}>固定 / 取消固定</Action></Card>)}{objects('inbox').filter(item=>text(item,'status')==='pending').map(item=><Card key={item.id}><Action secondary onClick={()=>void openObject(text(item,'object_id'))}>打开待处理来源</Action><Action secondary onClick={()=>command('inbox.dismiss',ref(item))}>忽略</Action></Card>)}</>}
      {screen==='object'&&object&&<Card><Badge value={text(object,'status')}/><h2>{text(object,'title')||text(object,'goal')||'来源记录'}</h2>{object.type==='brief'?<><p>{text(object,'proposal')}</p>{(object.data.facts as {task_id:string;title:string;status:string}[]).map(fact=><button className="live-item" key={fact.task_id} onClick={()=>go('tasks',fact.task_id)}>{fact.title}<Badge value={fact.status}/></button>)}<Action onClick={async()=>{const result=await command('brief.confirm',ref(object));if(result)void openObject(result.id)}}>已核对这张卡片</Action></>:<><Content value={object.data.content||object.data.text||object.data.summary||object.data.goal||object.data}/>{object.type==='task'&&<Action onClick={()=>go('tasks',object.id)}>进入任务</Action>}</>}<small>来源 ID {object.id} · 版本 {object.version}</small></Card>}
    </div>
    {screen==='home'&&activeTasks.length>0&&<button className="live-player" onClick={()=>go('tasks',activeTasks[0].id)}><span className="live-player-icon"><Sparkles size={19}/></span><span><small>任务播放器 · {activeTasks.length} 项待处理</small><strong>{text(activeTasks[0],'title')}</strong></span><Badge value={text(activeTasks[0],'status')}/></button>}
    <nav className="live-nav" aria-label="主导航">{([{id:'home',label:'首页',Icon:Home},{id:'messages',label:'消息',Icon:MessageCircle},{id:'knowledge',label:'知识',Icon:Library},{id:'profile',label:'我的',Icon:UserRound}] as const).map(({id,label,Icon})=><button key={id} aria-current={screen===id?'page':undefined} onClick={()=>go(id)}><Icon size={22}/><span>{label}</span></button>)}<button className="live-person" aria-label="新建任务" onClick={()=>go('tasks','new')}><Plus size={25}/></button></nav>
  </main>;
}

