"use client";
import {useEffect,useState} from 'react';
import {Card,Empty,Badge,Action,Form,Content} from './ui';
import {text,ref,type Snapshot,type Command,type Entity} from './types';
export function MessagesView({snapshot,command,selected,select,goTask}:{snapshot:Snapshot;command:Command;selected:string|null;select:(id:string|null)=>void;goTask:(id:string)=>void}){
  const [filter,setFilter]=useState('all');const objects=snapshot.objects,room=objects.conversation.find(item=>item.id===selected);
  if(room)return <Conversation key={room.id} room={room} snapshot={snapshot} command={command} back={()=>select(null)} goTask={goTask}/>;
  return <><div className="live-tabs">{[['all','全部'],['direct','私聊'],['group','群聊']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div>
    <details className="live-card"><summary>添加好友 / 创建群聊</summary><Form fields={[{name:'handle',label:'对方准确账号'},{name:'intro',label:'申请说明',required:false}]} submit="发送好友申请" onSubmit={async values=>command('friend.request',values)}/><hr/><Form fields={[{name:'title',label:'群名'},{name:'handles',label:'已接受关系的好友账号（逗号分隔）'}]} submit="创建群聊" onSubmit={async values=>{const result=await command('conversation.create',{title:values.title,handles:values.handles.split(/[,，]/).map(item=>item.trim()).filter(Boolean)});if(result)select(result.id)}}/></details>
    {objects.friend.filter(item=>text(item,'status')==='pending').map(item=><Card key={item.id}><small>{item.owner===snapshot.user.id?'你发出的申请':'收到的申请'}</small><p>{text(item,'intro')}</p><div className="live-actions">{item.data.recipient===snapshot.user.id?<><Action onClick={()=>command('friend.respond',{...ref(item),decision:'accept'})}>接受</Action><Action secondary onClick={()=>command('friend.respond',{...ref(item),decision:'decline'})}>拒绝</Action></>:<Action secondary onClick={()=>command('friend.respond',{...ref(item),decision:'withdraw'})}>撤回</Action>}</div></Card>)}
    {objects.conversation.filter(item=>filter==='all'||item.data.kind===filter).map(item=><button className="live-conversation" key={item.id} onClick={()=>{select(item.id);void command('conversation.read',{id:item.id,seq:item.data.seq})}}><span className="live-avatar">{text(item,'kind')==='group'?'群':text(item,'title')[0]}</span><span><strong>{text(item,'title')}</strong><small>{text(item,'kind')==='group'?'真人群聊':'真人私聊'} · {item.members?.length} 位成员</small></span>{Boolean(item.unread)&&<b>{item.unread}</b>}</button>)}
    {objects.conversation.length===0&&<Empty>还没有会话。添加好友并由对方接受后开始真人沟通。</Empty>}</>;
}
function Conversation({room,snapshot,command,back,goTask}:{room:Entity;snapshot:Snapshot;command:Command;back:()=>void;goTask:(id:string)=>void}){
  const objects=snapshot.objects,draft=objects.draft.find(item=>item.data.conversation_id===room.id),messages=objects.message||[];
  const [body,setBody]=useState(draft?text(draft,'text'):''),[helper,setHelper]=useState(false),[mentions,setMentions]=useState<string[]>([]),[context,setContext]=useState<string[]>([]),[loadedMessages,setLoadedMessages]=useState<Entity[]>([]);
  const assists=objects.assist.filter(item=>item.data.conversation_id===room.id);
  const savedText=draft?text(draft,'text'):'';
  useEffect(()=>{setBody(savedText)},[savedText]);
  useEffect(()=>{let active=true;const load=()=>fetch('/api/elfred/objects?type=message').then(response=>response.json()).then((value:unknown)=>{const items=value as Entity[];if(active&&Array.isArray(items))setLoadedMessages(items.filter(item=>item.space===room.id).sort((a,b)=>Number(a.data.seq)-Number(b.data.seq)))}).catch(()=>{});void load();const timer=setInterval(()=>void load(),2000);return()=>{active=false;clearInterval(timer)}},[room.id,room.data.seq]);
  const list=messages.length?messages.filter(item=>item.space===room.id):loadedMessages;
  return <><div className="live-section-title"><Action secondary onClick={back}>会话列表</Action><h2>{text(room,'title')}</h2></div><small>{room.members?.map(member=>member.name).join('、')}</small><div className="live-chat">{list.map(item=><div key={item.id} className={`live-message ${item.owner===snapshot.user.id?'mine':''}`}><small>{text(item,'sender_name')} · #{String(item.data.seq)}</small><p>{text(item,'text')}</p></div>)}{list.length===0&&<Empty>发送第一条真人消息。</Empty>}</div>
    <Card><label className="live-label">真人草稿<textarea aria-label="真人消息草稿" value={body} onChange={event=>setBody(event.target.value)} rows={3}/></label><div className="live-actions"><Action secondary onClick={()=>command('draft.save',{conversation_id:room.id,text:body,version:draft?.version??0})}>保存草稿</Action><Action secondary onClick={()=>setHelper(!helper)}>{room.data.kind==='direct'?'@ 本人辅助':'帮助我（仅本人）'}</Action><Action onClick={async()=>{if(await command('message.send',{id:room.id,text:body,mentions})){setBody('');setMentions([]);await command('draft.save',{conversation_id:room.id,text:'',version:draft?.version??0})}}}>发送给真人</Action></div>
    {room.data.kind==='group'&&<details><summary>@ 提及真人成员（发送后才通知）</summary>{room.members?.filter(member=>member.id!==snapshot.user.id).map(member=><label className="live-check" key={member.id}><input type="checkbox" checked={mentions.includes(member.id)} onChange={event=>setMentions(current=>event.target.checked?[...current,member.id]:current.filter(id=>id!==member.id))}/>{member.name}</label>)}</details>}</Card>
    {helper&&<section className="live-assist"><h3>仅你可见的沟通辅助</h3><p>先选择目的，明确运行后才调用。回填只修改草稿。</p><Form fields={[{name:'purpose',label:'需要怎样的帮助',type:'textarea',placeholder:'例如：温和拒绝这次邀请，保留以后联系的空间'}]} submit="选择辅助目的（暂不运行）" onSubmit={async values=>command('assist.create',{conversation_id:room.id,purpose:values.purpose})}/><details><summary>本次允许读取的消息</summary>{list.map(item=><label className="live-check" key={item.id}><input type="checkbox" checked={context.includes(item.id)} onChange={event=>setContext(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/>{text(item,'text').slice(0,80)}</label>)}</details>{assists.map(assist=>{const run=objects.run.find(item=>item.id===assist.data.run_id);const result=((run?.data.receipts||[]) as {output:unknown}[]).find(item=>typeof item.output==='string')?.output;return <Card key={assist.id}><p>{text(assist,'purpose')}</p>{!assist.data.run_id?<Form fields={[{name:'consent',label:'允许把目标与勾选消息发送给已配置的模型服务',type:'checkbox',required:true}]} submit="明确运行本人辅助" onSubmit={async()=>command('assist.run',{...ref(assist),confirm:true,model_consent:true,source_refs:context.map(id=>ref(list.find(item=>item.id===id) as Entity))})}/>:<><Badge value={run?text(run,'status'):'来源已失效'}/>{typeof result==='string'&&<><Content value={result}/><div className="live-actions">{['append','replace'].map(mode=><Action secondary key={mode} disabled={!draft} onClick={()=>command('assist.fill',{...ref(assist),run_id:run?.id,run_version:run?.version,mode,draft_version:draft?.version})}>{mode==='append'?'追加到草稿':'替换草稿'}</Action>)}</div>{!draft&&<small>请先保存真人草稿，再回填结果。</small>}</>}<Action secondary onClick={()=>goTask(text(assist,'task_id'))}>查看辅助任务及费用</Action></>}</Card>})}</section>}
    {room.data.kind==='group'&&<details className="live-card"><summary>群内共同事项与承诺</summary><Form fields={[{name:'goal',label:'候选事项'},{name:'assignee',label:'待确认负责人',type:'select',options:room.members?.map(member=>({value:member.id,label:member.name}))}]} submit="发布候选事项" onSubmit={async values=>command('commitment.create',{...values,conversation_id:room.id})}/>{objects.commitment.filter(item=>item.space===room.id).map(item=><Card key={item.id}><p>{text(item,'goal')}</p><Badge value={text(item,'status')}/>{item.data.assignee===snapshot.user.id&&text(item,'status')==='proposed'&&<div className="live-actions"><Action onClick={()=>command('commitment.respond',{...ref(item),accept:true})}>确认本人承诺</Action><Action secondary onClick={()=>command('commitment.respond',{...ref(item),accept:false})}>拒绝</Action></div>}{item.data.assignee===snapshot.user.id&&Boolean(item.data.task_id)&&<Action secondary onClick={()=>goTask(text(item,'task_id'))}>打开本人任务草稿</Action>}</Card>)}</details>}
    <details className="live-card"><summary>成员与关系管理</summary>{room.members?.filter(member=>member.id!==room.owner).map(member=><p key={member.id}>{member.name}{(room.owner===snapshot.user.id||member.id===snapshot.user.id)&&<Action secondary onClick={()=>command('conversation.remove_member',{...ref(room),user_id:member.id})}>{member.id===snapshot.user.id?'退出会话':'移除成员'}</Action>}</p>)}{objects.friend.filter(item=>item.data.conversation_id===room.id).map(item=><Action secondary key={item.id} onClick={()=>command('friend.respond',{...ref(item),decision:'block'})}>屏蔽这段关系</Action>)}</details>
  </>;
}

