"use client";
import {useState} from 'react';
import {Card,Empty,Badge,Action,Form,Content} from './ui';
import {text,ref,type Snapshot,type Command} from './types';
export function ProfileView({snapshot,command,logout}:{snapshot:Snapshot;command:Command;logout:()=>Promise<void>}){
  const [publicProfile,setPublicProfile]=useState<unknown>(null),[publicError,setPublicError]=useState('');
  const objects=snapshot.objects,profile=objects.profile[0],settings=objects.settings[0];
  return <><Card className="live-profile"><span className="live-avatar">{snapshot.user.name[0]}</span><h1>{snapshot.user.name}</h1><p>@{snapshot.user.handle}</p><small>私人资料与公开展示分别管理</small></Card>
    <details className="live-card"><summary>个人资料与访客预览</summary><Form fields={[{name:'name',label:'称呼',value:text(profile,'name')},{name:'bio',label:'简介',type:'textarea',value:text(profile,'bio'),required:false}]} submit="保存本人资料" onSubmit={async values=>command('profile.save',{...ref(profile),...values})}/><Form fields={[{name:'publish',label:'公开已保存的称呼与简介',type:'checkbox'},{name:'confirm',label:'已核对公开范围；任务、聊天与记忆仍保持私密',type:'checkbox',required:true}]} submit="更新公开展示" onSubmit={async values=>command('profile.publish',{...ref(profile),confirm:true,publish:values.publish==='on'})}/><Action secondary onClick={async()=>{setPublicError('');const response=await fetch('/api/elfred/profiles/'+encodeURIComponent(snapshot.user.handle));const result=await response.json() as {error:{message:string}};if(response.ok)setPublicProfile(result);else{setPublicProfile(null);setPublicError(result.error.message)}}}>用访客接口预览</Action>{publicProfile!==null&&<Content value={publicProfile}/>}<p>{publicError}</p></details>
    <Card><h3>模型与连接</h3><p>{snapshot.provider.configured?`已配置：${snapshot.provider.model}；以实际任务调用为准`:'模型尚未配置。请在本机 .env.local 填写服务地址、模型名和密钥，再重启。'}</p><small>Jev：尚未接通 · 判断基线：确定性规则</small><details><summary>安全配置说明</summary><p>在仓库根目录创建被 Git 忽略的 .env.local，按 config/local.env.example 填写 ELFRED_MODEL_BASE_URL、ELFRED_MODEL_NAME、ELFRED_MODEL_API_KEY。不要把密钥填入聊天或公开资料。</p></details>{objects.connector.map(item=><p key={item.id}>{text(item,'provider')} <Badge value={text(item,'status')}/>{text(item,'status')==='active'&&<Action secondary onClick={()=>command('connector.revoke',ref(item))}>撤销后续调用授权</Action>}</p>)}</Card>
    <details className="live-card"><summary>本地额度与费用记录</summary><p>总额度 {snapshot.budget.limit_units} · 已用 {snapshot.budget.spent} · 预留 {snapshot.budget.reserved}</p><p className="live-note">这些单位是本机防止无界调用的额度，不是货币。每次模型调用预留 1000 单位；真实供应商金额尚待费率与账单核对。</p><Form fields={[{name:'limit_units',label:'本地总额度上限',type:'number',value:String(snapshot.budget.limit_units)}]} submit="保存额度" onSubmit={async values=>command('budget.set',{limit_units:Number(values.limit_units)})}/>{snapshot.usage.map(item=><Card key={item.id}><small>{new Date(item.created).toLocaleString('zh-CN')}</small><p>{item.status==='unknown'?'调用结果待核对':item.status==='reserved'?'已预留':'本地额度已记账'} · {item.actual??item.reserved} 单位</p>{item.status==='unknown'&&<Form fields={[{name:'actual_units',label:'供应商核对后的本地实际额度',type:'number',value:String(item.reserved)},{name:'note',label:'核对依据'},{name:'confirm',label:'已检查供应商记录，确认本次对账',type:'checkbox',required:true}]} submit="记录对账并解除阻塞" onSubmit={async values=>command('usage.reconcile',{id:item.id,actual_units:Number(values.actual_units),note:values.note,confirm:true})}/>}</Card>)}</details>
    <details className="live-card"><summary>任务授权清单</summary>{objects.approval.length===0&&<Empty>尚无任务授权。</Empty>}{objects.approval.map(item=><Card key={item.id}><small>任务 {text(item,'task_id')}</small><p>范围：{(item.data.scopes as string[]).join('、')}</p><Badge value={text(item,'status')}/>{text(item,'status')==='approved'&&<Action secondary onClick={()=>command('approval.revoke',ref(item))}>撤销授权</Action>}</Card>)}</details>
    <details className="live-card"><summary>作息与通知</summary><Form fields={[{name:'timezone',label:'时区',value:text(settings,'timezone')},{name:'notifications',label:'启用私密轻提示',type:'checkbox'},{name:'quiet',label:'安静模式',type:'checkbox'}]} submit="保存设置" onSubmit={async values=>command('settings.save',{...ref(settings),timezone:values.timezone,notifications:values.notifications==='on',quiet:values.quiet==='on'})}/><small>应用内待办仍可查看。当前本地版没有向外部推送供应商发送通知。</small></details>
    <details className="live-card"><summary>连接资源</summary><Form fields={[{name:'title',label:'资源名称'},{name:'content',label:'可核对的公开或授权依据',type:'textarea'}]} submit="保存资源" onSubmit={async values=>command('resource.create',values)}/>{objects.resource.map(item=><Card key={item.id}><h3>{text(item,'title')}</h3><p>{text(item,'content')}</p><small>参与意愿：未知。保存不会发送邀请。</small></Card>)}</details>
    <Card><h3>账号与数据</h3><a className="live-secondary" href="/api/elfred/export" download>导出当前有权读取的数据</a><details><summary>登记数据删除请求</summary><Form fields={[{name:'confirm',label:'登记删除请求；处理范围将按数据保留政策核对',type:'checkbox',required:true}]} submit="登记删除请求" onSubmit={async()=>command('data.request',{kind:'delete',confirm:true})}/><p>当前删除请求会明确保留为待处理，不会冒称后台已清空数据。</p></details><Action secondary onClick={logout}>退出当前账号</Action></Card>
  </>;
}

