"use client";
import {useState} from 'react';
import {Card,Empty,Badge,Item,Action,Form,Content} from './ui';
import {text,ref,type Snapshot,type Command,type Entity} from './types';
export function TasksView({snapshot,selected,select,command,system,openObject}:{snapshot:Snapshot;selected:string|null;select:(id:string|null)=>void;command:Command;system?:string;openObject:(id:string)=>Promise<void>}){
  const [sources,setSources]=useState<string[]>([]);
  const objects=snapshot.objects,task=objects.task.find(item=>item.id===selected),run=objects.run.find(item=>item.id===task?.data.run_id);
  const receipts=(run?.data.receipts||[]) as {id:string;step_id:string;provider:string;effect_status:string;output:unknown;output_hash:string}[];
  if(task)return <><Action secondary onClick={()=>select(null)}>全部任务</Action><Card><div className="live-section-title"><Badge value={text(task,'status')}/><small>v{task.version}</small></div><h2>{text(task,'title')}</h2><p>{text(task,'goal')}</p><h3>验收标准</h3><p>{text(task,'criteria')}</p><small>{text(task,'constraints')}</small><p className="live-note">任务验收与满意度分别记录。自动检索检查仅确认回执与来源；生成内容需要本人核对。</p>
    {text(task,'status')==='draft'&&<Form fields={[{name:'confirm',label:'确认目标、资料范围和有限调用额度',type:'checkbox',required:true},...(text(task,'mode')==='compose'?[{name:'consent',label:'允许把本次目标与所选资料发送给已配置的模型服务',type:'checkbox' as const,required:true}]:[])]} submit="确认任务" onSubmit={async values=>command('task.confirm',{...ref(task),confirm:values.confirm==='on',model_consent:values.consent==='on'})}/>}
    {['ready','blocked','failed','partial','paused','cancelled'].includes(text(task,'status'))&&<Action onClick={()=>command('run.start',ref(task))}>启动 / 恢复运行</Action>}
    {run&&['queued','running'].includes(text(run,'status'))&&<div className="live-actions"><Action secondary onClick={()=>command('run.command',{...ref(run),command:'pause'})}>暂停</Action><Action secondary onClick={()=>command('run.command',{...ref(run),command:'cancel'})}>取消</Action></div>}
    {run?.data.error? <p className="live-error">{String((run.data.error as {message:string}).message)}</p>:null}
    {['awaiting_acceptance','awaiting_review'].includes(text(task,'status'))&&<Form fields={[{name:'decision',label:'核对本次成果',type:'select',options:[{value:'accept',label:'符合目标，验收成果'},{value:'reject',label:'仍有缺口，退回修改'}]},{name:'satisfaction',label:'满意度（独立于验收）',type:'select',options:[{value:'unknown',label:'暂不评价'},{value:'satisfied',label:'满意'},{value:'unsatisfied',label:'不满意'}]},{name:'feedback',label:'补充反馈',required:false},{name:'confirm',label:'我已阅读下方成果及其来源',type:'checkbox',required:true}]} submit="提交验收" onSubmit={async values=>command('task.accept',{...ref(task),accept:values.decision==='accept',satisfaction:values.satisfaction,feedback:values.feedback})}/>}
    {text(task,'status')==='completed'&&<Action onClick={()=>openObject(text(task,'artifact_id'))}>查看知识成果</Action>}</Card>
    {run&&<Card><h3>真实执行记录</h3><Badge value={text(run,'status')}/><p>已执行步骤：{receipts.length} / {((run.data.plan as {steps:unknown[]})?.steps||[]).length}</p><small>累计调用 {String(task.data.calls)} · 已用本地额度 {String(task.data.units)} · 满意度 {text(task,'satisfaction')}</small>{run.data.verification?<Content value={run.data.verification}/>:null}{receipts.map(receipt=><section className="live-receipt" key={receipt.id}><small>{receipt.step_id} · {receipt.provider} · {receipt.effect_status}</small>{Array.isArray(receipt.output)?(receipt.output as {id:string;title:string;excerpt:string}[]).map(hit=><div key={hit.id}><button className="live-link" onClick={()=>void openObject(hit.id)}>{hit.title}</button><p>{hit.excerpt}</p></div>):<Content value={receipt.output}/>}<details><summary>回执校验信息</summary><small>{receipt.id}<br/>{receipt.output_hash}</small></details></section>)}</Card>}
    {text(task,'status')==='completed'&&<Card><h3>保存为可复用方法</h3><Form fields={[{name:'title',label:'方法名'},{name:'instructions',label:'适用场景和步骤',type:'textarea'}]} submit="保存方法草稿" onSubmit={async values=>command('skill.create',{...values,task_id:task.id})}/></Card>}
    <details className="live-card"><summary>目标版本与停止条件</summary><Content value={task.data.stop}/><small>Task {task.id}<br/>Run {run?.id||'尚未启动'}</small></details></>;
  return <>{system&&<Card><h2>{snapshot.systems.find(item=>item.id===system)?.name}系统</h2><p>只接收本次选择的资料。未核对的理解保持待验证。</p><div className="live-chips">{snapshot.definitions.filter(item=>item.system===system).map(item=><span key={item.id} title={item.limitations||'按任务启动'}>{item.name}</span>)}</div><small>专业能力按任务加载；未配置外部工具的能力不会伪装成执行成功。</small></Card>}
    <div className="live-section-title"><h2>{system?'向本人 Agent 提出目标':'从目标创建任务'}</h2></div><Card><Form fields={[{name:'goal',label:'想完成什么',type:'textarea',placeholder:'明确你希望得到的结果'},{name:'criteria',label:'怎样算完成',value:'核对返回资料与来源；生成内容由本人审核'},{name:'mode',label:'本次执行方式',type:'select',options:[{value:'compose',label:'生成文字草稿（需要模型服务）'},{value:'search',label:'检索应用内资料（本地可用）'},{value:'read',label:'读取所选文本文件（本地可用）'}]},{name:'system',label:'主责系统',type:'select',value:system||'create',options:snapshot.systems.map(item=>({value:item.id,label:item.name}))}]} submit="保存任务草稿" onSubmit={async values=>{const result=await command('task.create',{...values,source_refs:sources.map(id=>{const item=[...objects.document,...objects.knowledge].find(item=>item.id===id) as Entity;return ref(item)})});if(result){setSources([]);select(result.id)}}}><fieldset><legend>选择本次资料（可不选）</legend>{[...objects.document,...objects.knowledge].length===0?<small>尚无资料，可在知识页上传。</small>:[...objects.document,...objects.knowledge].map(item=><label key={item.id} className="live-check"><input type="checkbox" checked={sources.includes(item.id)} onChange={event=>setSources(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/>{text(item,'title')}</label>)}</fieldset></Form></Card>
    <h2>任务列表</h2>{objects.task.filter(item=>!system||item.data.system===system).length===0?<Empty>尚无任务。保存草稿后，确认范围再启动。</Empty>:objects.task.filter(item=>!system||item.data.system===system).map(item=><Item key={item.id} item={item} onClick={()=>select(item.id)}/>)}</>;
}
