"use client";
import {useState} from 'react';
import {Action,Field} from './runtime-panels';
import {useRuntime,entityRef} from './runtime-context';
import {type Entity,text} from '../features/live/types';
export function MemoryEvidence({item}:{item:Entity}) {
  const runtime=useRuntime()!,[outcome,setOutcome]=useState(''),[scenario,setScenario]=useState(''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false);
  const levels:Record<string,string>={insufficient:'依据不足',explicit:'本人明确确认',scenario_verified:'具体情境已验证',hypothesis:'有反证，待重新核对',stable_over_time:'跨时间验证'};
  const evidence=(item.data.evidence||[]) as {outcome_id:string;scenario:string;note:string}[];
  return <section className="v277-edit-card"><h3>理解依据 · {levels[text(item,'alignment')]||'依据不足'}</h3>{evidence.map(entry=><p key={entry.outcome_id}>{entry.scenario}：{entry.note}</p>)}{item.data.status==='validated'&&<><label className="v277-field"><span>已验收成果</span><select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">选择实际成果</option>{runtime.snapshot!.objects.outcome.filter(entry=>entry.data.verdict==='accepted'&&!evidence.some(e=>e.outcome_id===entry.id)).map(entry=><option key={entry.id} value={entry.id}>{runtime.snapshot!.objects.task.find(task=>task.id===entry.data.task_id)?.data.title as string||entry.id}</option>)}</select></label><Field name="验证场景" value={scenario} onChange={setScenario}/><Field name="这次成果如何支持这条理解" value={note} onChange={setNote} area/><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已核对成果与这条理解之间的依据</label><Action disabled={!outcome||!scenario.trim()||!note.trim()||!confirmed} run={async()=>{await runtime.command('memory.evidence',{...entityRef(item),outcome_id:outcome,scenario,note,confirm:true});setOutcome('');setNote('');setConfirmed(false)}}>记录这次验证</Action><details><summary>记录反证或核对跨时间稳定性</summary><p>不会按次数或天数自动升级。请说明最近证据、适用范围与反证的处理。</p>{((item.data.counterevidence||[]) as {note:string;resolved_at?:string}[]).map((entry,index)=><p key={index}>{entry.resolved_at?'已核对':'待处理反证'}：{entry.note}</p>)}<Field name="核对说明" value={note} onChange={setNote} area/><Action disabled={!note.trim()||!confirmed} run={()=>runtime.command('memory.counterevidence',{...entityRef(item),note,confirm:true})}>记录与理解不符的情况</Action><Action disabled={evidence.length<2||!note.trim()||!confirmed} run={()=>runtime.command('memory.review_stability',{...entityRef(item),note,confirm:true,resolve_counterevidence:true})}>确认多次情境持续成立，反证已核对</Action></details></>}</section>;
}
