"use client";
import {ReleaseDetail} from '../features/home/community-works';
import {OriginLinks} from '../features/messages/result-handoffs';
import {ProjectWork,CopyWork} from '../features/home/project-work';

import {useState,type ReactNode} from 'react';
import {ArrowLeft,ChevronRight,FileText,Check} from 'lucide-react';
import {useRuntime,entityRef} from './runtime-context';
import {type Entity,text,statuses} from '../features/live/types';
import {ProjectSlots,ArtifactPreview} from '../features/home/project-slots';
import {CommunityComposer,CommunityDiscussion} from '../features/home/community-post';
import {ImprovementPanel} from './improvement-panel';
import {objectScreen} from './object-screen';
import type {Screen} from './screen';

type Go=(screen:Screen)=>void;
export function ConversationMembers({conversation,onLeave}:{conversation:Entity;onLeave:()=>void}) {
  const runtime=useRuntime()!,user=runtime.snapshot!.user.id;
  const [title,setTitle]=useState(String(conversation.data.title)),[invite,setInvite]=useState(''),[successor,setSuccessor]=useState('');
  if(conversation.data.kind!=='group')return null;
  return <section className="v277-edit-card"><h3>群成员</h3>{user===conversation.owner&&<><Field name="群名称" value={title} onChange={setTitle}/><Action disabled={!title.trim()||title===conversation.data.title} run={()=>runtime.command('conversation.rename',{...entityRef(conversation),title})}>保存群名</Action><label className="v277-field">新成员可见的历史<select value={String(conversation.data.history_policy||'all')} onChange={e=>void runtime.command('conversation.history_policy',{...entityRef(conversation),policy:e.target.value,confirm:true}).catch(()=>{})}><option value="all">全部历史</option><option value="from_join">仅入群后的消息</option></select></label><p>范围在邀请时确定，修改规则不扩大已入群成员的历史权限。</p><label className="v277-field">移交群主<select value={successor} onChange={e=>setSuccessor(e.target.value)}><option value="">选择接任成员</option>{conversation.members?.filter(m=>m.id!==user).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><Action disabled={!successor} run={()=>runtime.command('conversation.transfer_owner',{...entityRef(conversation),user_id:successor,confirm:true})}>确认移交管理权</Action><Field name="邀请好友账号" value={invite} onChange={setInvite}/><Action disabled={!invite.trim()} run={async()=>{await runtime.command('conversation.invite',{...entityRef(conversation),handle:invite});setInvite('')}}>邀请已接受关系的好友</Action></>}{conversation.members?.map(member=><div key={member.id}><span>{member.name} · @{member.handle}</span>{member.id!==conversation.owner&&(user===conversation.owner||user===member.id)&&<Action run={async()=>{await runtime.command('conversation.remove_member',{...entityRef(conversation),user_id:member.id});if(user===member.id)onLeave()}}>{user===member.id?'退出此群':'移除此成员'}</Action>}</div>)}</section>;
}
export function InboxPage({go,onBack}:{go:Go;onBack:()=>void}){
 return <main className="v277-page elfred-inbox-page"><Header title="收件箱" onBack={onBack}/><InboxPanel go={go}/></main>;
}
function InboxPanel({go}:{go:Go}) {
 const runtime=useRuntime()!,snapshot=runtime.snapshot!,[tab,setTab]=useState('pending');
 const objects=Object.values(snapshot.objects).flat(),items=snapshot.objects.inbox.filter(item=>item.data.status===tab);
 return <section className="v277-edit-card elfred-inbox-panel"><h3>本人收件箱</h3><p>保存想稍后处理的内容。整理为任务后，仍需你确认才会启动。</p><nav aria-label="收件箱分类">{[['pending','待整理'],['processed','已转任务'],['dismissed','已处理']].map(([status,title])=><button type="button" key={status} aria-pressed={tab===status} onClick={()=>setTab(status)}>{title} · {snapshot.objects.inbox.filter(item=>item.data.status===status).length}</button>)}</nav>{!items.length&&<p className="v277-empty">{tab==='pending'?'暂无待整理内容，可以从首页动态存入。':'这里还没有记录。'}</p>}{items.map(item=>{const object=objects.find(entry=>entry.id===item.data.object_id);return <article key={item.id}><h4>{text(item,'title')||text(object,'title')||text(object,'name')||'已保存事项'}</h4><p>{(text(item,'summary')||text(object,'summary')||text(object,'content')||text(object,'goal')).slice(0,180)}</p><small>存入于 {new Date(item.created).toLocaleString('zh-CN')}</small><div className="elfred-inbox-actions"><button type="button" className="v277-secondary" disabled={!object} onClick={()=>object&&go(objectScreen(object))}>打开原记录</button>{item.data.task_id?<button type="button" className="v277-secondary" onClick={()=>go({name:'task',id:String(item.data.task_id)})}>查看任务</button>:tab==='pending'&&[['execute','整理为行动草稿'],['explore','继续研究'],['create','用于创作']].map(([system,label])=><Action key={system} run={async()=>{const result=await runtime.command('inbox.task',{...entityRef(item),system});go({name:'task',id:result.id})}}>{label}</Action>)}{tab==='pending'&&<Action run={()=>runtime.command('inbox.dismiss',entityRef(item))}>标记已处理</Action>}{tab==='dismissed'&&<Action run={async()=>{await runtime.command('inbox.create',{object_id:item.data.object_id});setTab('pending')}}>放回待整理</Action>}</div></article>})}</section>;
}
export const label=(item:Entity)=>statuses[text(item,'status')]||text(item,'status');
export function Field({name,value,onChange,area=false,type='text'}:{name:string;value:string;onChange:(v:string)=>void;area?:boolean;type?:string}) {
  return <label className="v277-field"><span>{name}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;
}
export function Action({children,run,disabled=false}:{children:ReactNode;run:()=>Promise<unknown>;disabled?:boolean}) {
  const [busy,setBusy]=useState(false);
  return <button type="button" className="v277-secondary" disabled={disabled||busy} onClick={()=>{setBusy(true);void run().catch(()=>{}).finally(()=>setBusy(false))}}>{busy?'正在保存…':children}</button>;
}
function Header({title,onBack}:{title:string;onBack:()=>void}) {return <header className="v277-page-head"><button className="v277-icon-button" type="button" aria-label="返回" onClick={onBack}><ArrowLeft size={21}/></button><div><h1>{title}</h1></div><span className="v277-head-right"/></header>}
export function AssetEditor({onSaved}:{onSaved?:(id:string)=>void}) {
  const runtime=useRuntime()!;
  const [kind,setKind]=useState('knowledge'),[title,setTitle]=useState(''),[content,setContent]=useState('');
  return <section className="v277-edit-card"><label className="v277-field"><span>保存类型</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="knowledge">知识笔记</option><option value="memory">待确认理解</option><option value="resource">资源</option></select></label><Field name="标题 / 用途" value={title} onChange={setTitle}/><Field name="内容" value={content} onChange={setContent} area/><Action disabled={!title.trim()||!content.trim()} run={async()=>{const result=await runtime.command(kind+'.create',kind==='memory'?{content,purpose:title,scope:'owner',risk:'high'}:{title,content});setContent('');onSaved?.(result.id)}}>保存到本人资料</Action><label className="v277-field"><span>导入 UTF-8 文本（txt / md / csv / json，最大 500 KB）</span><input type="file" accept=".txt,.md,.csv,.json" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>500000){runtime.report('文件不能超过 500 KB');return;}void file.text().then(content=>runtime.command('document.create',{title:file.name,content})).then(result=>onSaved?.(result.id)).catch(()=>{});e.target.value='';}}/></label></section>;
}
export function ConnectedUtility({kind,go,onBack}:{kind:string;go:Go;onBack:()=>void}) {
  const runtime=useRuntime()!,snapshot=runtime.snapshot!;
  const [handle,setHandle]=useState(''),[group,setGroup]=useState(''),[handles,setHandles]=useState('');
  const titles:Record<string,string>={'add-friend':'添加联系人',relationships:'关系',notifications:'通知',ability:'能力洞察',level:'理解与对齐',honors:'成长记录',tools:'我的工具'};
  const relation=kind==='add-friend'||kind==='relationships';
  return <main className="v277-page v278-utility-page"><Header title={titles[kind]||'资料'} onBack={onBack}/>
    {kind==='notifications'&&<InboxPanel go={go}/>}
    {relation?<><section className="v278-utility-form"><h2>通过账号建立联系</h2><Field name="对方账号" value={handle} onChange={setHandle}/><Action disabled={!handle.trim()} run={async()=>{await runtime.command('friend.request',{handle});setHandle('')}}>发送站内好友申请</Action></section>
      <section className="v278-utility-list">{snapshot.objects.friend.map(item=><article className="v277-edit-card" key={item.id}><b>{text(item,'other_name')} · @{text(item,'other_handle')}</b><p>{text(item,'intro')}</p><p>{label(item)}</p>{text(item,'status')==='pending'?(item.data.recipient===snapshot.user.id?<><Action run={()=>runtime.command('friend.respond',{...entityRef(item),decision:'accept'})}>接受申请</Action><Action run={()=>runtime.command('friend.respond',{...entityRef(item),decision:'decline'})}>拒绝申请</Action></>:<Action run={()=>runtime.command('friend.respond',{...entityRef(item),decision:'withdraw'})}>撤回申请</Action>):null}{item.data.status==='accepted'&&<><button className="v277-secondary" onClick={()=>go({name:'chat',id:text(item,'conversation_id')})}>打开会话</button><Action run={()=>runtime.command('friend.respond',{...entityRef(item),decision:'remove'})}>解除好友关系</Action><Action run={()=>runtime.command('friend.respond',{...entityRef(item),decision:'block'})}>屏蔽</Action></>}</article>)}</section>
      <section className="v277-edit-card"><h3>创建群聊</h3><Field name="群名" value={group} onChange={setGroup}/><Field name="已接受的好友账号，以逗号分隔" value={handles} onChange={setHandles}/><Action disabled={!group.trim()||!handles.trim()} run={async()=>{const result=await runtime.command('conversation.create',{title:group,handles:handles.split(/[,，\s]+/).filter(Boolean)});go({name:'chat',id:result.id})}}>创建群聊</Action></section></>:kind==='notifications'?<section className="v278-utility-list">{snapshot.objects.notification.length===0&&<p className="v277-empty">暂时没有通知</p>}{snapshot.objects.notification.map(item=><button key={item.id} onClick={()=>{void runtime.command('notification.read',entityRef(item)).then(()=>{const target=Object.values(snapshot.objects).flat().find(t=>t.id===item.data.target_id);if(target)go(objectScreen(target));else runtime.report('通知对应内容已撤下或当前不可访问')}).catch(()=>{})}}><span><Check size={20}/></span><div><b>{text(item,'summary')}</b><p>{item.data.status==='unread'?'未读':'已读'} · {new Date(item.created).toLocaleString('zh-CN')}</p></div><ChevronRight size={19}/></button>)}</section>:<><section className="v278-utility-list"><button onClick={()=>go({name:'tasks'})}><span><Check size={20}/></span><div><b>{snapshot.objects.task.filter(t=>t.data.status==='completed').length} 项已验收任务</b><p>结果、满意度与理解分别记录，不换算成虚构评分。</p></div><ChevronRight size={19}/></button><button onClick={()=>go({name:'memory'})}><span><FileText size={20}/></span><div><b>{snapshot.objects.memory.filter(t=>t.data.status==='validated').length} 条本人确认的理解</b><p>点击核对依据、修正或撤销。</p></div><ChevronRight size={19}/></button></section><MethodsPanel go={go}/></>}
  </main>;
}

export function ConnectedSettings({active,go}:{active:string;go:Go}) {
  const runtime=useRuntime()!,snapshot=runtime.snapshot!,settings=snapshot.objects.settings[0],profile=snapshot.objects.profile[0];
  const [limit,setLimit]=useState(String(snapshot.budget.limit_units)),[note,setNote]=useState(''),[zone,setZone]=useState(text(settings,'timezone'));
  return <div className="v279-setting-options">{active==='account'?<><p>{snapshot.user.name} · @{snapshot.user.handle}</p><p>账号密码登录，当前会话最长七天。短信与第三方登录尚未配置。</p><Field name="时区" value={zone} onChange={setZone}/><Action run={()=>runtime.command('settings.save',{...entityRef(settings),...settings.data,timezone:zone})}>保存时区</Action></>:active==='notifications'?<><Action run={()=>runtime.command('settings.save',{...entityRef(settings),...settings.data,notifications:!settings.data.notifications})}>{settings.data.notifications?'关闭':'开启'}站内提醒</Action><Action run={()=>runtime.command('settings.save',{...entityRef(settings),...settings.data,quiet:!settings.data.quiet})}>{settings.data.quiet?'关闭':'开启'}免打扰</Action></>:active==='understanding'?<><p>已确认 {snapshot.objects.memory.filter(item=>item.data.status==='validated').length} 条；待核对 {snapshot.objects.memory.filter(item=>['candidate','pending_confirmation'].includes(text(item,'status'))).length} 条。</p><button onClick={()=>go({name:'memory'})}>查看与修正记忆</button></>:active==='privacy'?<><p>公开主页仅含本人选择公开的称呼和简介。</p><Action run={()=>runtime.command('profile.publish',{...entityRef(profile),confirm:true,publish:!profile.data.public})}>{profile.data.public?'设为仅自己可见':'确认公开称呼和简介'}</Action><h3>任务授权</h3>{snapshot.objects.approval.filter(item=>item.data.status==='approved').map(item=><div key={item.id}><p>{snapshot.objects.task.find(task=>task.id===item.data.task_id)?.data.title as string} · {String(item.data.scopes)}</p><Action run={()=>runtime.command('approval.revoke',entityRef(item))}>撤销该授权</Action></div>)}</>:active==='data'?<><p>模型：{snapshot.provider.configured?snapshot.provider.model:'未配置'}；判定：{snapshot.provider.judge}；Jev：{snapshot.provider.jev}</p><p>额度 {snapshot.budget.limit_units}，已用 {snapshot.budget.spent}，预留 {snapshot.budget.reserved}。这是本地调用配额，不代表人民币费用。</p><Field name="本地额度上限" value={limit} onChange={setLimit} type="number"/><Action run={()=>runtime.command('budget.set',{limit_units:Number(limit)})}>保存额度</Action><a className="v277-secondary" href="/api/elfred/export" download="elfred-export.json">导出本人当前可访问的数据</a><Field name="供应商对账依据" value={note} onChange={setNote}/>{snapshot.usage.filter(item=>item.status==='unknown').map(item=><UsageReconcile key={item.id} id={item.id} reserved={item.reserved} note={note}/>)}<h3>已归档任务</h3>{snapshot.objects.task.filter(item=>item.data.status==='archived').map(item=><div key={item.id}><p>{text(item,'title')}</p><Action run={()=>runtime.command('task.restore',entityRef(item))}>恢复此任务</Action></div>)}<p>外部服务密钥仅保存在服务端环境文件中；浏览器不展示密钥。</p></>:active==='appearance'?<p>当前使用原版 V28 浅色外观。</p>:<><p>本地服务数据保存于 SQLite。先创建任务草稿，确认目标和资料，再启动；模型结果需本人验收。知识和消息只按当前权限读取。</p><AssetEditor/></>}</div>;
}
function UsageReconcile({id,reserved,note}:{id:string;reserved:number;note:string}) {const runtime=useRuntime()!;const [actual,setActual]=useState('');return <div><p>待对账预留 {reserved}</p><Field name="核对后的实际本地额度" value={actual} onChange={setActual} type="number"/><Action disabled={!note.trim()||!actual} run={()=>runtime.command('usage.reconcile',{id,confirm:true,note,actual_units:Number(actual)})}>确认对账记录</Action></div>}

export function PrivateAssist({conversation,onFill,go}:{conversation:Entity;onFill:(text:string)=>void;go:Go}) {
  const runtime=useRuntime()!,snapshot=runtime.snapshot!;
  const [purpose,setPurpose]=useState(''),[selected,setSelected]=useState<string[]>([]),[consent,setConsent]=useState(false),[assignee,setAssignee]=useState(snapshot.user.id);
  const messages=snapshot.objects.message.filter(item=>item.space===conversation.id),assists=snapshot.objects.assist.filter(item=>item.data.conversation_id===conversation.id),draft=snapshot.objects.draft.find(item=>item.data.conversation_id===conversation.id);
  return <section className="v277-edit-card"><h3>@ 本人私密辅助</h3><p>只由你查看。选择消息和用途后单独授权运行；回填草稿后仍由你发送。</p><div>{['起草回复','解释所选消息','整理待办与负责人','整理会议结论和分歧','提取日程候选','形成今日群简报'].map(choice=><button className="v277-secondary" key={choice} onClick={()=>setPurpose(choice+'，仅根据所选消息，不补造未知事实。')}>{choice}</button>)}</div><Field name="辅助目的 / 候选事项" value={purpose} onChange={setPurpose} area/>{messages.slice(-20).map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>setSelected(prev=>prev.includes(item.id)?prev.filter(id=>id!==item.id):[...prev,item.id])}/>{text(item,'sender_name')}：{text(item,'text').slice(0,100)}</label>)}<Action disabled={!purpose.trim()} run={()=>runtime.command('assist.create',{conversation_id:conversation.id,purpose})}>创建私密辅助</Action><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意将此目的及所选消息发给已配置模型</label>{assists.map(item=><article key={item.id}><p>{text(item,'purpose')} · {label(item)}</p>{!item.data.task_id?<Action disabled={!consent} run={()=>runtime.command('assist.run',{...entityRef(item),confirm:true,model_consent:true,source_refs:messages.filter(message=>selected.includes(message.id)).map(entityRef)})}>运行辅助</Action>:<><button className="v277-secondary" onClick={()=>go({name:'task',id:text(item,'task_id')})}>查看辅助任务</button><Action run={()=>runtime.command('assist.save_note',{...entityRef(item),run_id:snapshot.objects.task.find(t=>t.id===item.data.task_id)?.data.run_id,run_version:snapshot.objects.run.find(r=>r.id===snapshot.objects.task.find(t=>t.id===item.data.task_id)?.data.run_id)?.version})}>保存为本人笔记</Action>{(['append','replace'] as const).map(mode=><Action key={mode} run={async()=>{const draftVersion=draft?.version??(await runtime.command('draft.save',{conversation_id:conversation.id,text:'',version:0})).version;const result=await runtime.command('assist.fill',{...entityRef(item),run_id:snapshot.objects.task.find(t=>t.id===item.data.task_id)?.data.run_id,run_version:snapshot.objects.run.find(r=>r.id===snapshot.objects.task.find(t=>t.id===item.data.task_id)?.data.run_id)?.version,draft_version:draftVersion,mode});const updated=await runtime.request<Entity>('/objects/'+result.id);onFill(text(updated,'text'))}}>{mode==='append'?'追加到':'替换'}草稿</Action>)}</>}</article>)}{Boolean(draft?.data.previous)&&<Action run={async()=>{const result=await runtime.command('draft.save',{conversation_id:conversation.id,text:draft!.data.previous,version:draft!.version});const restored=await runtime.request<Entity>('/objects/'+result.id);onFill(text(restored,'text'))}}>恢复上次草稿</Action>}
    {conversation.data.kind==='group'&&<><h3>群聊候选事项</h3><label className="v277-field"><span>负责人</span><select value={assignee} onChange={e=>setAssignee(e.target.value)}>{conversation.members?.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><Action disabled={!purpose.trim()} run={()=>runtime.command('commitment.create',{conversation_id:conversation.id,goal:purpose,assignee})}>提议事项（需负责人接受）</Action>{snapshot.objects.commitment.filter(item=>item.space===conversation.id).map(item=><div key={item.id}><p>{text(item,'goal')} · {label(item)}</p>{item.data.assignee===snapshot.user.id&&item.data.status==='proposed'&&<><Action run={async()=>{const result=await runtime.command('commitment.respond',{...entityRef(item),accept:true});if(result.task_id)go({name:'task',id:result.task_id})}}>接受并创建本人任务草稿</Action><Action run={()=>runtime.command('commitment.respond',{...entityRef(item),accept:false})}>拒绝事项</Action></>}</div>)}</>}
  </section>;
}

export function ConnectedProject({id,onBack,go}:{id:string;onBack:()=>void;go:Go}) {
  const runtime=useRuntime()!,snapshot=runtime.snapshot!,post=snapshot.objects.post.find(item=>item.id===id),project=snapshot.objects.project.find(item=>item.id===(post?.data.project_id||id));
  const [title,setTitle]=useState(''),[goal,setGoal]=useState(''),[criteria,setCriteria]=useState(''),[task,setTask]=useState(''),[participation,setParticipation]=useState('open'),[comment,setComment]=useState(''),[fork,setFork]=useState(false),[toolDescription,setToolDescription]=useState('');
  const owner=project?.owner===snapshot.user.id;
  const release=snapshot.objects.release.find(r=>r.id===id);if(release)return <ReleaseDetail key={release.id} release={release} go={go} onBack={onBack}/>;
  if(id==='new')return <CommunityComposer onBack={onBack} go={go}/>;
  if(post&&!post.data.project_id)return <CommunityDiscussion key={post.id} post={post} onBack={onBack} go={go}/>;
  if(!post&&!project)return <main className="v277-page"><Header title="内容当前不可访问" onBack={onBack}/><p className="v277-empty">内容可能已撤下，或你已不具备访问权限。</p></main>;
  return <main className="v277-page v278-social-detail"><Header title={id==='new'?'发起协作项目':'项目与讨论'} onBack={onBack}/>{id==='new'?<section className="v277-edit-card"><Field name="项目名称" value={title} onChange={setTitle}/><Field name="共同目标" value={goal} onChange={setGoal} area/><Field name="验收标准" value={criteria} onChange={setCriteria} area/><Field name="开放任务" value={task} onChange={setTask} area/><label className="v277-field"><span>参与方式</span><select value={participation} onChange={e=>setParticipation(e.target.value)}><option value="open">确认后参与</option><option value="application">申请后由发起者批准</option></select></label><Action disabled={![title,goal,criteria,task].every(v=>v.trim())} run={async()=>{const result=await runtime.command('project.create',{title,goal,criteria,task,participation});go({name:'community-post',id:result.id})}}>创建私有项目草稿</Action></section>:<>
      <article className="v278-social-article"><h2>{text(project||post!,'title')}</h2><p>{text(project||post!,'goal')||text(post!,'content')}</p><p>验收：{text(project||post!,'criteria')}</p><p>任务：{text(project||post!,'task')}</p>{!project&&post&&post.data.status==='recruiting'&&!(post.data.slots as unknown[]|undefined)?.length&&<Action run={async()=>{const result=await runtime.command('project.claim',{post_id:post.id,confirm:true});if(post.data.participation==='open')go({name:'community-post',id:result.project_id!});else runtime.report('申请已提交，等待发起者批准')}}>确认本人参与承诺并{post.data.participation==='application'?'申请':'加入'}</Action>}{owner&&<><Action run={()=>runtime.command('project.publish_post',{...entityRef(project!),confirm:true})}>确认公开以上项目资料</Action><Action run={()=>runtime.command('project.recruiting',{...entityRef(project!),enabled:!project!.data.recruiting})}>{project!.data.recruiting?'停止招募':'重新开放招募'}</Action></>}{post&&<><Action run={()=>runtime.command('post.interact',{id:post.id,kind:'save'})}>切换收藏</Action><Action run={()=>runtime.command('post.interact',{id:post.id,kind:'report'})}>标记 / 取消举报</Action></>}</article>
      <OriginLinks targetId={project?.id||id} go={go}/><ProjectSlots project={project} post={post}/>{project&&<ProjectWork project={project} go={go} onBack={onBack}/>}{project&&<><section className="v277-edit-card"><h3>正式成果 · 修订 {String(project.data.revision)}</h3><p style={{whiteSpace:'pre-wrap'}}>{text(project,'content')||'尚无采纳成果'}</p>{(owner||!snapshot.objects.project_slot.some(s=>s.space===project.id))&&<Action run={()=>runtime.command('copy.create',{project_id:project.id})}>创建本人独立工作副本</Action>}</section>{snapshot.objects.copy.filter(item=>item.data.project_id===project.id).map(item=><CopyEditor key={item.id} item={item} go={go}/>)}{snapshot.objects.contribution.filter(item=>item.data.project_id===project.id).map(item=><ContributionReview key={item.id} item={item} owner={!!owner}/>)}<section className="v277-edit-card"><h3>项目成员与申请</h3>{project.members?.map(member=><p key={member.id}>{member.name} · {member.role}{owner&&member.id!==snapshot.user.id&&<Action run={()=>runtime.command('project.remove_member',{...entityRef(project),user_id:member.id})}>移除项目成员</Action>}</p>)}{owner&&snapshot.objects.claim.filter(item=>item.data.project_id===project.id&&item.data.status==='pending').map(item=><div key={item.id}><p>申请参与：{text(item,'goal')}</p><Action run={()=>runtime.command('claim.review',{...entityRef(item),accept:true})}>批准</Action><Action run={()=>runtime.command('claim.review',{...entityRef(item),accept:false})}>拒绝</Action></div>)}</section><section className="v277-edit-card"><h3>阶段反馈</h3>{snapshot.objects.feedback.filter(item=>item.space===project.id).map(item=><p key={item.id}>{text(item,'content')}</p>)}<Field name="阶段进展、阻塞或依赖" value={comment} onChange={setComment} area/><Action disabled={!comment.trim()} run={async()=>{await runtime.command('project.feedback',{id:project.id,content:comment});setComment('')}}>提交反馈</Action></section>{owner&&<section className="v277-edit-card"><h3>发布与回滚</h3><Field name="作品使用的工具与 AI 协作说明（可选）" area value={toolDescription} onChange={setToolDescription}/><label><input type="checkbox" checked={fork} onChange={e=>setFork(e.target.checked)}/>授予署名再创作许可</label><Action disabled={!project.data.accepted_contribution} run={()=>runtime.command('project.release',{...entityRef(project),confirm:true,allow_fork:fork,tool_description:toolDescription})}>确认公开发布已采纳成果</Action></section>}</>}
      {snapshot.objects.release.filter(item=>item.data.project_id===(project?.id||post?.data.project_id)).map(item=><section key={item.id} className="v277-edit-card"><h3>发布版本 {String(item.data.revision)}{(project?.data.release_id||post?.data.release_id)===item.id?' · 当前':''}</h3><ArtifactPreview item={item}/><p>贡献者：{((item.data.contributors||[]) as {name:string}[]).map(c=>c.name).join("、")||"此历史版本尚未记录完整贡献名单"}</p><p style={{whiteSpace:'pre-wrap'}}>{text(item,'content')}</p>{owner&&<Action run={()=>runtime.command('project.rollback',{...entityRef(project!),release_id:item.id})}>将此版设为当前发布</Action>}{item.data.license==='copy-with-attribution'&&<><Field name="再创作目标" value={goal} onChange={setGoal}/><Action disabled={!goal.trim()} run={async()=>{const result=await runtime.command('project.fork',{release_id:item.id,goal});go({name:'community-post',id:result.id})}}>创建独立再创作项目</Action></>}</section>)}
      {post&&<section className="v278-comment-list"><h3>评论</h3>{(snapshot.objects.comment||[]).filter(item=>item.data.post_id===post.id).map(item=><article key={item.id}><p>{text(item,'author_name')}：{text(item,'content')}</p></article>)}<Field name="发表评论" value={comment} onChange={setComment}/><Action disabled={!comment.trim()} run={async()=>{await runtime.command('post.comment',{id:post.id,content:comment});setComment('')}}>确认发布评论</Action></section>}
    </>}</main>;
}
function CopyEditor({item,go}:{item:Entity;go:Go}) {
  const runtime=useRuntime()!;
  const [content,setContent]=useState(text(item,'content')),[format,setFormat]=useState(text(item,'format')||'text'),[reviewed,setReviewed]=useState(false);
  const [base,setBase]=useState({version:item.version,content:text(item,'content'),format:text(item,'format')||'text'});
  const stale=item.data.status==='draft'&&item.version!==base.version;
  return <section className="v277-edit-card"><h3>本人副本 · {label(item)}</h3><CopyWork copy={item} go={go}/>
    {Boolean(item.data.origin_copy)&&<details open><summary>当前正式成果（请合并保留其他人的贡献）</summary><p style={{whiteSpace:'pre-wrap'}}>{text(item,'upstream_content')||'尚无正文'}</p></details>}
    <label className="v277-field"><span>成果格式</span><select disabled={item.data.status!=='draft'} value={format} onChange={e=>{setFormat(e.target.value);setReviewed(false)}}><option value="text">文本成果</option><option value="web">可运行网页（HTML 与项目内 CSS / JS 文件）</option></select></label><ArtifactPreview item={item}/>
    <Field name="成果正文" value={content} onChange={value=>{setContent(value);setReviewed(false)}} area/>
    {stale&&<div><p>此副本已在其他页面修改。请先复制保留你的文字，再载入最新版本核对合并。</p><button className="v277-secondary" onClick={()=>{setBase({version:item.version,content:text(item,'content'),format:text(item,'format')||'text'});setFormat(text(item,'format')||'text');setContent(text(item,'content'));setReviewed(false)}}>载入最新副本</button></div>}
    {item.data.status==='draft'&&<><Action disabled={stale||(content===base.content&&format===base.format)||!content.trim()} run={async()=>{const result=await runtime.command('copy.save',{id:item.id,version:base.version,content,format});setBase({version:result.version!,content,format})}}>保存副本</Action><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>{item.data.origin_copy?'已核对并合并当前正式成果，保留其他人的贡献':'已核对本人贡献与验收标准'}</label><Action disabled={stale||!reviewed||content!==base.content||format!==base.format} run={()=>runtime.command('copy.submit',{id:item.id,version:base.version,reviewed:true})}>提交已保存的贡献</Action></>}
    {item.data.status==='submitted'&&<Action run={()=>runtime.command('copy.revise',entityRef(item))}>基于最新正式成果创建修订副本</Action>}
  </section>;
}
function ContributionReview({item,owner}:{item:Entity;owner:boolean}) {const runtime=useRuntime()!;const [feedback,setFeedback]=useState('');return <section className="v277-edit-card"><h3>贡献 · {label(item)}</h3><ArtifactPreview item={item}/><p style={{whiteSpace:'pre-wrap'}}>{text(item,'content')}</p><p>{text(item,'feedback')}</p>{Boolean((item.data.conflict_files as string[]|undefined)?.length)&&<p role="alert">冲突文件：{(item.data.conflict_files as string[]).join("、")}。请回到本人副本合并后重新提交。</p>}<details><summary>提交时的验收约定与文件</summary><p>{String((item.data.rules_snapshot as {criteria?:string})?.criteria||"")}</p>{Object.entries(item.data.files as Record<string,string>||{}).map(([name,content])=><details key={name}><summary>{name}</summary><pre style={{whiteSpace:"pre-wrap"}}>{content}</pre></details>)}</details>{owner&&item.data.status==='submitted'&&<><Field name="审查反馈" value={feedback} onChange={setFeedback}/>{[['accept','采纳'],['changes','要求修改'],['reject','拒绝']].map(([decision,title])=><Action key={decision} run={()=>runtime.command('contribution.review',{...entityRef(item),decision,feedback})}>{title}</Action>)}</>}</section>}

export function MethodsPanel({go}:{go:Go}) {
  const runtime=useRuntime()!,snapshot=runtime.snapshot!;
  const [title,setTitle]=useState(''),[instructions,setInstructions]=useState(''),[taskId,setTaskId]=useState('');
  return <section className="v277-edit-card"><h3>可复用方法</h3>{snapshot.objects.skill.map(item=><div key={item.id}><b>{text(item,'title')}</b><p>{text(item,'instructions')}</p><Action run={()=>runtime.command('shortcut.pin',{skill_id:item.id})}>{snapshot.objects.shortcut.some(shortcut=>shortcut.data.skill_id===item.id&&shortcut.data.pinned)?'取消快捷入口':'固定为快捷入口'}</Action><Action run={async()=>{const result=await runtime.command('task.create',{goal:text(item,'instructions'),system:'execute',mode:'compose'});go({name:'task',id:result.id})}}>创建复用任务草稿</Action></div>)}<label className="v277-field"><span>已验收任务依据</span><select value={taskId} onChange={e=>setTaskId(e.target.value)}><option value="">选择已验收任务</option>{snapshot.objects.task.filter(item=>item.data.status==='completed').map(item=><option key={item.id} value={item.id}>{text(item,'title')}</option>)}</select></label><Field name="方法名" value={title} onChange={setTitle}/><Field name="可复用步骤" value={instructions} onChange={setInstructions} area/><Action disabled={!taskId||!title.trim()||!instructions.trim()} run={()=>runtime.command('skill.create',{task_id:taskId,title,instructions})}>保存方法草稿</Action><ImprovementPanel go={go}/></section>;
}
