import {fail,hash,now} from './store.mjs';
import {bodyFor,localSearch,semanticSources} from './search-engine.mjs';
import {taskCommand} from './runtime.mjs';
import {DEFAULT_STOP} from './policy.mjs';
const MAX_CHUNKS=40;
function chunksOf(text){const chunks=[];let content='',bytes=0,line=1,start=1;for(const ch of text){const size=Buffer.byteLength(ch,'utf8');if(bytes+size>1600){if(content.trim())chunks.push({text:content,anchor:'line:'+start});content='';bytes=0;start=line;}content+=ch;bytes+=size;if(ch==='\n')line++;}if(content.trim())chunks.push({text:content,anchor:'line:'+start});return chunks;}
export function semanticScope(store,user,input){
 const base=localSearch(store,user,input);if(base.status!=='complete')return {...base,plan_key:null,chunks:[],total_chunks:0};const intent=base.intent,offset=input.semantic_offset||0;
 if(!Number.isInteger(offset)||offset<0)fail('INVALID_INPUT','语义检索分页范围不正确');
 const sources=semanticSources(store,user,input,intent);
 const all=sources.flatMap(o=>{const body=bodyFor(store,user,o);if(!body.trim()||intent.exclude.some(word=>body.toLowerCase().includes(word.toLowerCase())))return [];const title=o.type==='profile'&&o.owner!==user?o.data.published?.name||'公开资料':o.data.title||o.data.name||body.slice(0,60);return chunksOf(body).map((chunk,index)=>({...chunk,id:o.id,version:o.version,type:o.type,title,origin_id:o.search_origin_id||null,chunk:index}));});
 const chunks=all.slice(offset,offset+MAX_CHUNKS),scope_key=hash(JSON.stringify(all.map(c=>[c.id,c.version,c.chunk]))),plan_key=hash(JSON.stringify({query_id:base.query_id,scope_key,offset,chunks}));
 return {status:'complete',query_id:base.query_id,intent:base.intent,plan_key,scope_key,chunks,total_chunks:all.length,offset,next_offset:offset+chunks.length<all.length?offset+chunks.length:null};
}
export function semanticPreview(store,user,input){const scope=semanticScope(store,user,input);return {...scope,chunks:scope.chunks.map(({text,...metadata})=>({...metadata,characters:text.length,excerpt:text.slice(0,100)})),max_calls:Math.ceil(scope.chunks.length/10),max_units:Math.ceil(scope.chunks.length/10)*1000,max_tokens:100000};}
export function semanticCommand(store,user,action,input){
 if(action!=='search.semantic')return null;if(input.confirm!==true||input.model_consent!==true)fail('CONSENT_REQUIRED','请核对本次语义检索范围与额度');const scope=semanticScope(store,user,input);
 if(!scope.plan_key||scope.plan_key!==input.plan_key)fail('SEARCH_SCOPE_CHANGED','来源或查询已变化，请刷新范围后重新核对');if(!scope.chunks.length)fail('CANDIDATES_REQUIRED','此范围没有可读文字');
 let previous=[];
 if(input.semantic_previous_id){const prior=store.owned(user,input.semantic_previous_id,'task');if(!prior.data.search_semantic||prior.data.search_query_id!==scope.query_id||prior.data.semantic_plan.scope_key!==scope.scope_key||prior.data.semantic_plan.next_offset!==scope.offset)fail('SEARCH_SCOPE_CHANGED','前后批次的范围已变化，请重新从首批检索');const priorRun=store.owned(user,prior.data.run_id,'run');if(priorRun.data.checkpoint.length!==priorRun.data.plan.steps.length)fail('INVALID_STATE','请先恢复并完成上一批，再检索下一批');previous=[...(prior.data.semantic_previous_ids||[]),prior.id];if(previous.length>=50)fail('STOP_LIMIT','本轮已完成 50 批，请缩小搜索范围后继续');}
 const refs=[...new Map(scope.chunks.map(c=>[c.id,{id:c.id,version:c.version}])).values()];
 const task=taskCommand(store,user,'task.create',{goal:'语义查找：'+input.query,criteria:'返回有来源的相关候选；相似度不等于满足条件',system:'explore',source_refs:[],review_mode:'single',stop:{...DEFAULT_STOP,maxCalls:Math.ceil(scope.chunks.length/10),maxUnits:Math.ceil(scope.chunks.length/10)*1000,maxTokens:100000}});
 const batches=[];for(let i=0;i<scope.chunks.length;i+=10)batches.push({id:'semantic-'+i/10,tool:'text.compose',phase:'semantic',depends:[],chunks:scope.chunks.slice(i,i+10)});
 store.update(store.get(task.id),{...store.get(task.id).data,internal_search:true,search_semantic:true,semantic_previous_ids:previous,media_operation:'embedding_search',source_refs:refs,search_query_id:scope.query_id,search_intent:scope.intent,semantic_plan:{batches,offset:scope.offset,total_chunks:scope.total_chunks,next_offset:scope.next_offset,plan_key:scope.plan_key,scope_key:scope.scope_key}},user);
 taskCommand(store,user,'task.confirm',{id:task.id,version:store.get(task.id).version,confirm:true,model_consent:true});const run=taskCommand(store,user,'run.start',{id:task.id,version:store.get(task.id).version});return {id:task.id,task_id:task.id,run_id:run.id};
}
export function semanticResults(store,user,input){
 const task=store.owned(user,input.semantic_task_id,'task');if(!task.data.search_semantic)fail('INVALID_CONTEXT','不是语义检索任务');const run=store.owned(user,task.data.run_id,'run'),base=localSearch(store,user,input);if(task.data.search_query_id!==base.query_id)fail('QUERY_CHANGED','查询已改变，请重新进行语义检索');
 const allowed=new Set(semanticSources(store,user,input,base.intent).map(o=>o.id));
 const runs=[...(task.data.semantic_previous_ids||[]).map(id=>{const prior=store.owned(user,id,'task');if(prior.data.search_query_id!==base.query_id||prior.data.semantic_plan.scope_key!==task.data.semantic_plan.scope_key)fail('SEARCH_SCOPE_CHANGED','批次范围不一致，请重新检索');return store.owned(user,prior.data.run_id,'run');}),run],chunks=run.data.plan.steps.flatMap(s=>s.chunks||[]),seen=new Map(),processed=new Set();
 for(const current of runs){const frozen=current.data.plan.steps.flatMap(s=>s.chunks||[]);for(const receipt of current.data.receipts||[]){if(receipt.phase!=='semantic')continue;let results;try{results=JSON.parse(receipt.output)}catch{continue;}if(!Array.isArray(results))continue;for(const result of results){const chunk=frozen.find(c=>c.id===result.id&&c.version===result.version&&c.chunk===result.chunk);if(!chunk||!allowed.has(chunk.id)||!Number.isFinite(result.score))continue;const source=store.get(chunk.id);if(!source||source.version!==chunk.version||!store.canRead(user,source))continue;processed.add(chunk.id+':'+chunk.version+':'+chunk.chunk);const previous=seen.get(chunk.id);if(!previous||result.score>previous.score)seen.set(chunk.id,{...chunk,score:result.score});}}}
 const dense=[...seen.values()].sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)),merged=new Map(base.hits.map((hit,index)=>[hit.id,{...hit,score:1/(60+index+1),channels:hit.channels||[]}])) ;
 dense.forEach((chunk,index)=>{const score=1/(60+index+1),hit=merged.get(chunk.id);if(hit){hit.score+=score;hit.channels=[...new Set([...hit.channels,'vector'])];return;}const checks=base.intent.conditions.map(condition=>({condition,status:'unknown',evidence:'',anchor:null}));if(base.intent.latest)checks.push({condition:'最新有效版本',status:store.get(chunk.id)?.data.is_current===true?'satisfied':'unknown',evidence:'',anchor:null});merged.set(chunk.id,{id:chunk.id,version:chunk.version,type:chunk.type,title:chunk.title,excerpt:chunk.text.slice(0,500),anchor:chunk.anchor,score,origin_id:chunk.origin_id||null,channels:['vector'],condition_checks:checks,condition_status:'unknown',semantic_status:'similarity_only'});});
 return {...base,hits:[...merged.values()].sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)).slice(0,50),checked_at:now(),engine:'keyword-relation-vector-rrf',semantic_status:'similarity_only',coverage:{processed_chunks:(run.data.receipts||[]).filter(r=>r.phase==='semantic').reduce((n,r)=>n+(run.data.plan.steps.find(s=>s.id===r.step_id)?.chunks.length||0),0),accumulated_chunks:processed.size,batch_chunks:chunks.length,total_chunks:task.data.semantic_plan.total_chunks,offset:task.data.semantic_plan.offset,next_offset:task.data.semantic_plan.next_offset,status:runs.every(r=>r.data.checkpoint.length===r.data.plan.steps.length)?'complete':'partial'}};
}
