"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { ArrowLeft, ArrowRight, Bell, Bookmark, Check, ChevronDown, ChevronRight, Clock3, Heart, ListChecks, LockKeyhole, MessageCircle, MoreHorizontal, Plus, Search, Send, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, X, Zap } from "lucide-react";
import { AgentSetupFields, RhythmBreakdown } from "./agent-setup-fields";
import { AgentAvatar, agentLevel, agents, posts, useProduct, type AgentId, type Post, type Task } from "./product-state";

function Panel({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
  const ref=useRef<HTMLElement>(null);
  useEffect(()=>{const prior=document.activeElement as HTMLElement;const first=ref.current?.querySelector<HTMLElement>("button,input,textarea");first?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();if(e.key==="Tab"){const nodes=ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),textarea,select,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);prior?.focus();};},[]);
  const target=typeof document!=="undefined"?document.querySelector(".phone-stage"):null;
  if(!target)return null;
  return createPortal(<div className="v-overlay" role="dialog" aria-modal="true" aria-label={title}><section ref={ref} className="v-panel"><header className="v-panel-head"><button className="v-icon" onClick={onClose} aria-label="返回"><ArrowLeft size={21}/></button><strong>{title}</strong><button className="v-icon" onClick={onClose} aria-label="关闭"><X size={19}/></button></header><div className="v-panel-body">{children}</div></section></div>,target);
}

function TaskList({agent}:{agent?:AgentId}){
  const {state,setState,addTask}=useProduct();const [filter,setFilter]=useState("全部");const [title,setTitle]=useState("");const [selected,setSelected]=useState<AgentId>(agent||"execute");const [type,setType]=useState<Task["type"]>("一次性");
  const tasks=state.tasks.filter(t=>(!agent||t.agent===agent)&&(filter==="全部"||t.status===filter));
  return <><div className="v-pills">{["全部","待确认","进行中","已完成"].map(f=><button key={f} className={filter===f?"selected":""} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="v-form-card"><label htmlFor="task-title">交给小队一件事</label><input id="task-title" value={title} maxLength={180} onChange={e=>setTitle(e.target.value)} placeholder="写下具体的目标…"/><div className="v-two-fields">{!agent&&<label>负责 Agent<select value={selected} onChange={e=>setSelected(e.target.value as AgentId)}>{agents.map(a=><option key={a.id} value={a.id}>{state.configs[a.id].name}</option>)}</select></label>}<label>任务类型<select value={type} onChange={e=>setType(e.target.value as Task["type"])}>{["一次性","周期性","条件触发"].map(t=><option key={t}>{t}</option>)}</select></label></div><button className="v-primary" disabled={!title.trim()} onClick={()=>{addTask(selected,title.trim(),undefined,type);setTitle("");}}>创建任务草稿 <Plus size={17}/></button></div><div className="v-task-list">{tasks.length===0&&<div className="v-empty"><ListChecks size={28}/><h3>这里还没有{filter==="全部"?"任务":filter+"的任务"}</h3><p>从朋友圈带回一条发现，或者写下想做的事情。</p></div>}{tasks.map(t=><article key={t.id} className="v-card v-task-card"><div className="v-inline-label"><span className={`v-tag ${t.status==="已完成"?"green":""}`}>{t.status}</span><small>{t.type} · {state.configs[t.agent].name}</small></div><h3>{t.title}</h3><p>{t.source?"来自朋友圈的想法":"用户创建的任务"} · 仅本机演示</p>{t.status==="待确认"&&<div className="v-task-plan"><span>01 明确目标与交付范围</span><span>02 收集材料并准备草稿</span><span>03 由你检查结果，再决定下一步</span></div>}<div className="v-button-row">{t.status!=="已完成"?<button className="v-secondary" onClick={()=>setState(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?{...x,status:t.status==="待确认"?"进行中":"已完成"}:x)}))}>{t.status==="待确认"?"确认并模拟开始":"模拟完成任务"}<Check size={16}/></button>:<button className="v-secondary" onClick={()=>setState(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?{...x,status:"待确认"}:x)}))}>重新打开</button>}<button className="v-icon" aria-label="移除任务草稿" onClick={()=>setState(s=>({...s,tasks:s.tasks.filter(x=>x.id!==t.id)}))}><Trash2 size={17}/></button></div></article>)}</div><p className="v-note">任务状态用于演示流程，不会触发工具调用或后台定时执行。</p></>;
}

function Memories({agent}:{agent:AgentId}){
  const {state,setState}=useProduct();const [text,setText]=useState("");const list=state.memories.filter(m=>m.agent===agent||m.agent==="global");
  return <><div className="v-callout"><ShieldCheck size={20}/><p>确认过的偏好才会作为长期记忆。锁定后不会被反馈自动覆盖。</p></div><form className="v-input-action v-memory-add" onSubmit={e=>{e.preventDefault();if(text.trim()){setState(s=>({...s,memories:[{id:crypto.randomUUID(),agent,text:text.trim(),confirmed:true,locked:false,source:"手动添加"},...s.memories]}));setText("");}}}><input aria-label="新增记忆" value={text} maxLength={240} onChange={e=>setText(e.target.value)} placeholder="告诉它一条重要偏好…"/><button type="submit" aria-label="保存记忆" disabled={!text.trim()}><Plus size={18}/></button></form>{list.length===0&&<div className="v-empty"><ShieldCheck size={28}/><h3>留白，是了解的开始</h3><p>初始化设定、已确认评论和手动补充，会汇集在这里。</p></div>}{list.map(m=><div key={m.id} className="v-card v-memory-card"><div className="v-inline-label"><span className={`v-tag ${m.confirmed?"green":""}`}>{m.confirmed?"已确认":"待你确认"}</span><small>{m.agent==="global"?"共享目标":m.source}</small></div><textarea aria-label="编辑记忆" disabled={m.locked} value={m.text} maxLength={240} onChange={e=>setState(s=>({...s,memories:s.memories.map(x=>x.id===m.id?{...x,text:e.target.value}:x)}))}/><div className="v-button-row">{!m.confirmed&&<button className="v-text" onClick={()=>setState(s=>({...s,memories:s.memories.map(x=>x.id===m.id?{...x,confirmed:true}:x)}))}><Check size={15}/>确认这条记忆</button>}<button className="v-text" onClick={()=>setState(s=>({...s,memories:s.memories.map(x=>x.id===m.id?{...x,locked:!x.locked}:x)}))}><LockKeyhole size={14}/>{m.locked?"解除锁定":"锁定"}</button><button className="v-text" disabled={m.locked} onClick={()=>setState(s=>({...s,memories:s.memories.filter(x=>x.id!==m.id)}))}><Trash2 size={14}/>删除</button></div></div>)}</>;
}

function Growth({agent}:{agent:AgentId}){
  const {state}=useProduct();const data=agentLevel(state,agent);const [selected,setSelected]=useState(6);
  const stages=["初识期","初识期","初识期","对齐期","对齐期","懂你期","协作期","协作期","协作期","托付期","托付期","托付期","分身期","分身期","分身期"];
  return <><div className="v-growth-hero"><small>一起走过的阶段</small><h2>L{data.level}<span> / 15</span></h2><p>{stages[data.level-1]} · 每条被确认的理解，都比一次点击重要。</p></div><div className="v-level-grid">{Array.from({length:15},(_,i)=>i+1).map(n=><button key={n} className={`${n<=data.level?"done":""} ${selected===n?"selected":""} ${n===6?"milestone":""}`} onClick={()=>setSelected(n)}>L{n}{n===6&&<small>懂你</small>}</button>)}</div><div className="v-card v-stage-detail"><span className="v-tag">L{selected} · {stages[selected-1]}</span><h3>{selected<4?"开始认识你的方向":selected<6?"逐渐形成稳定偏好":selected===6?"在这个领域，开始懂你":selected<10?"成为稳定的长期搭档":selected<13?"在明确规则内获得托付":"持续代表你处理复杂目标"}</h3><p>等级不是操作授权。对外发送、付款、删除与公开发布始终需要单独确认。</p></div><section className="v-card v-growth-checks"><h3>通向 L6 的真实条件</h3>{[["稳定目标",data.goals,3],["已确认偏好",data.prefs,20],["有效反馈",data.feedback,30],["垂直任务完成",data.done,10]].map(([label,current,target])=><div key={label}><span>{label}<small>{current} / {target}</small></span><progress value={Number(current)} max={Number(target)}/></div>)}<div className="v-verification"><LockKeyhole size={18}/><p>还需验证最近 20 次真实推荐的正向反馈率。当前为演示数据，暂不授予 L6“懂你”认证。</p></div></section></>;
}

function AgentSpace({id,onPost}:{id:AgentId;onPost:(post:Post)=>void}){
  const {state,setState,addTask,notify}=useProduct();const a=agents.find(a=>a.id===id)!;const config=state.configs[id];const [tab,setTab]=useState("主页");const [draft,setDraft]=useState("");const [messages,setMessages]=useState<{role:"user"|"agent";text:string}[]>([]);const [editing,setEditing]=useState(false);const data=agentLevel(state,id);
  const submit=()=>{if(!draft.trim())return;const value=draft.trim();setMessages(s=>[...s,{role:"user",text:value},{role:"agent",text:`我把这个目标记为：“${value}”。建议先明确交付内容和时间，再整理参考材料，最后形成一份由你确认的草稿。下面可以将它加入${a.name}任务台。`}]);setDraft("");};
  return <><div className="v-agent-profile"><AgentAvatar id={id} size="large"/><div><small>{a.role}</small><h1>{config.name||a.name}<span>L{data.level}</span></h1><p>{a.desc}</p></div><button className="v-icon" onClick={()=>setEditing(!editing)} aria-label="编辑 Agent 设定"><Settings2 size={18}/></button></div><div className="v-pills v-agent-tabs">{["主页","对话","任务","记忆","养成"].map(t=><button key={t} className={tab===t?"selected":""} onClick={()=>setTab(t)}>{t}</button>)}</div>{editing&&<div className="v-form-card"><label>Agent 名称<input aria-label="Agent 名称" maxLength={12} value={config.name} onChange={e=>setState(s=>({...s,configs:{...s.configs,[id]:{...config,name:e.target.value}}}))}/></label><label>表达方式<select value={config.style} onChange={e=>setState(s=>({...s,configs:{...s.configs,[id]:{...config,style:e.target.value,mode:"custom"}}}))}>{a.styles.map(st=><option key={st}>{st}</option>)}</select></label><AgentSetupFields id={id}/><label>补充要求<textarea value={config.note} maxLength={240} onChange={e=>setState(s=>({...s,configs:{...s.configs,[id]:{...config,note:e.target.value,mode:"custom"}}}))}/></label><label className="v-switch-row"><span><strong>暂停内容推荐</strong><small>保留记忆与任务，不再显示它的帖子</small></span><input type="checkbox" checked={config.paused} onChange={e=>setState(s=>({...s,configs:{...s.configs,[id]:{...config,paused:e.target.checked}}}))}/></label><button className="v-primary" onClick={()=>{setEditing(false);notify("Agent 设定已保存到当前浏览器。");}}>完成</button></div>}
    {tab==="主页"&&<><div className="v-card v-agent-understanding"><div className="v-inline-label"><h3>正在了解你</h3><span className="v-tag green">{config.mode==="default"?"探索期":"已初始化"}</span></div><p>{config.note||a.defaults}</p><div className="v-chips">{(config.topics.length?config.topics:["等待你的第一个选择"]).map(t=><span key={t}>{t}</span>)}</div><button className="v-text" onClick={()=>setTab("记忆")}>查看 {state.memories.filter(m=>m.agent===id||m.agent==="global").length} 条记忆 <ArrowRight size={15}/></button></div><h3 className="v-section-title">现在可以交给我</h3><button className="v-capability-card" onClick={()=>{setDraft(a.prompt);setTab("对话");}}><a.icon size={22}/><div><strong>{a.action}</strong><p>{a.prompt}</p></div><ChevronRight size={18}/></button><div className="v-mini-stats"><button onClick={()=>setTab("任务")}><b>{state.tasks.filter(t=>t.agent===id&&t.status!=="已完成").length}</b><span>待推进任务</span></button><button onClick={()=>setTab("养成")}><b>{data.feedback}</b><span>有效反馈</span></button></div><button className="v-primary" onClick={()=>setTab("对话")}>和{config.name}聊聊 <MessageCircle size={17}/></button><section className="v-agent-recent"><h3 className="v-section-title">近期产出</h3>{posts.filter(post=>post.agent===id).map(post=><button key={post.id} className="v-recent-output" onClick={()=>onPost(post)}><span><small>{post.category} · {post.time}</small><strong>{post.title}</strong></span><ChevronRight size={18}/></button>)}</section><p className="v-note">资料、任务与对话均为本机原型体验，尚未连接真实模型。</p></>}
    {tab==="对话"&&<div className="v-agent-conversation"><div className="v-callout"><Sparkles size={18}/><p>当前为演示对话。可以描述任务、查看草稿并加入任务台。</p></div><div className="v-chat-bubble"><small>{config.name} · 示例回复</small><p>{a.desc}你可以直接说目标，也可以从下面的建议开始。</p></div>{messages.map((m,i)=><div key={i} className={`v-chat-bubble ${m.role==="user"?"user":""}`}><small>{m.role==="user"?"你":`${config.name} · 示例回复`}</small><p>{m.text}</p>{m.role==="agent"&&<button className="v-text" onClick={()=>addTask(id,messages[i-1].text)}>加入任务草稿 <Plus size={15}/></button>}</div>)}{messages.length===0&&<button className="v-suggestion" onClick={()=>setDraft(a.prompt)}>{a.prompt}<ArrowRight size={15}/></button>}<form className="v-chat-composer" onSubmit={e=>{e.preventDefault();submit();}}><input aria-label={`与${config.name}对话`} value={draft} maxLength={500} onChange={e=>setDraft(e.target.value)} placeholder={`交给${config.name}一件事…`}/><button type="submit" aria-label="发送" disabled={!draft.trim()}><Send size={18}/></button></form></div>}
    {tab==="任务"&&<TaskList agent={id}/>} {tab==="记忆"&&<Memories agent={id}/>} {tab==="养成"&&<Growth agent={id}/>}</>;
}

function PostView({post,onAgent,onTasks}:{post:Post;onAgent:(id:AgentId)=>void;onTasks:()=>void}){
  const {state,setState,addTask,notify}=useProduct();const [comment,setComment]=useState("");const [choice,setChoice]=useState("");const [more,setMore]=useState(false);const [reason,setReason]=useState("");const a=agents.find(a=>a.id===post.agent)!;const comments=[...post.comments,...(state.comments[post.id]||[])];const memories=state.memories.filter(m=>m.source===post.id&&!m.confirmed);
  const feedback=()=>setState(s=>({...s,feedback:{...s.feedback,[post.agent]:(s.feedback[post.agent]||0)+1}}));
  const submit=()=>{const value=comment.trim();if(!value)return;setState(s=>({...s,comments:{...s.comments,[post.id]:[...(s.comments[post.id]||[]),{id:crypto.randomUUID(),author:"user",text:value},{id:crypto.randomUUID(),author:post.agent,text:"演示回复：收到你的看法。我先把原话记为待确认信息，不会直接覆盖已有偏好。"}]},memories:[{id:crypto.randomUUID(),agent:post.agent,text:value,confirmed:false,locked:false,source:post.id},...s.memories],feedback:{...s.feedback,[post.agent]:(s.feedback[post.agent]||0)+1}}));setComment("");notify("你的评论已保存，有一条记忆等待你确认。");};
  return <><div className="v-post-detail-heading"><button className="v-post-author" onClick={()=>onAgent(post.agent)}><AgentAvatar id={post.agent}/><span><strong>{state.configs[post.agent].name} Agent</strong><small>{post.time} · {post.category}示例</small></span></button><button className="v-icon" onClick={()=>setMore(!more)} aria-label="更多操作"><MoreHorizontal size={20}/></button></div><span className="v-tag">{post.label}</span><h1 className="v-post-title">{post.title}</h1><p className="v-post-full-text">{post.body}</p><div className="v-card v-source-card"><h3>为什么推荐给你</h3><p>{post.reason}</p><p>{post.relation}</p><small>产品原型 · 示例内容，非实时外部资讯</small></div>{post.decision&&<div className="v-decision-box"><strong>你怎么看？</strong><div className="v-chips">{(post.id==="p4"?["喜欢 A","喜欢 B"]:["认同这个方向","我有不同想法"]).map(v=><button key={v} className={state.votes[post.id]===v?"selected":""} onClick={()=>{setState(s=>({...s,votes:{...s.votes,[post.id]:v}}));feedback();setChoice(v);}}>{v}</button>)}</div>{choice&&<p className="v-subtle">已记录选择。可以在评论里补充理由，或再次点击修改。</p>}</div>}
      {more&&<div className="v-form-card"><label>为什么不感兴趣</label><div className="v-chips">{["与当前目标无关","内容重复","不喜欢这个方向"].map(v=><button key={v} className={reason===v?"selected":""} onClick={()=>setReason(v)}>{v}</button>)}</div><button className="v-secondary" onClick={()=>{setState(s=>({...s,hidden:[...new Set([...s.hidden,post.id])],memories:reason?[{id:crypto.randomUUID(),agent:post.agent,text:`对“${post.title}”的反馈：${reason}`,confirmed:true,locked:false,source:"不感兴趣反馈"},...s.memories]:s.memories}));setMore(false);notify("已从主页隐藏，可在内容设置中恢复。");}}>隐藏这条内容</button></div>}
      <div className="v-post-actionbar"><button className={state.likes.includes(post.id)?"active":""} onClick={()=>{setState(s=>({...s,likes:s.likes.includes(post.id)?s.likes.filter(x=>x!==post.id):[...s.likes,post.id]}));feedback();}}><Heart size={18}/>{state.likes.includes(post.id)?"已喜欢":"喜欢"}</button><button className={state.saves.includes(post.id)?"active":""} onClick={()=>setState(s=>({...s,saves:s.saves.includes(post.id)?s.saves.filter(x=>x!==post.id):[...s.saves,post.id]}))}><Bookmark size={18}/>{state.saves.includes(post.id)?"已收藏":"收藏"}</button><button onClick={()=>{if(!state.tasks.some(t=>t.source===post.id))addTask(post.agent,post.title,post.id);onTasks();}}><Plus size={18}/>转成任务</button></div>
      <h3 className="v-section-title">一起讨论 <small>{comments.length}</small></h3><div className="v-comments">{comments.map(c=><article key={c.id}>{c.author==="user"?<span className="v-person-avatar small">{(state.profile.name||"我").slice(0,1)}</span>:<button className="v-avatar-button" onClick={()=>onAgent(c.author as AgentId)}><AgentAvatar id={c.author}/></button>}<div><strong>{c.author==="user"?state.profile.name||"我":state.configs[c.author].name}</strong><p>{c.text}</p></div></article>)}{comments.length===0&&<p className="v-subtle">说说你的看法，让{a.name}更了解你。</p>}</div>{memories.map(m=><div className="v-callout v-memory-confirm" key={m.id}><ShieldCheck size={18}/><div><strong>要记住这条反馈吗？</strong><p>{m.text}</p><div className="v-button-row"><button className="v-text" onClick={()=>setState(s=>({...s,memories:s.memories.map(x=>x.id===m.id?{...x,confirmed:true}:x)}))}>确认记住</button><button className="v-text" onClick={()=>setState(s=>({...s,memories:s.memories.filter(x=>x.id!==m.id)}))}>仅本次讨论</button></div></div></div>)}<form className="v-chat-composer" onSubmit={e=>{e.preventDefault();submit();}}><input aria-label="发表评论" placeholder="你的看法很重要…" value={comment} maxLength={500} onChange={e=>setComment(e.target.value)}/><button type="submit" disabled={!comment.trim()} aria-label="发布评论"><Send size={18}/></button></form></>;
}


export function AgentHome({onCommunity,onSchedule}:{onCommunity:()=>void;onSchedule:()=>void}){
  const {state,setState,notice,notify,restart,addTask}=useProduct();
  const [filter,setFilter]=useState("推荐");const [query,setQuery]=useState("");const [panel,setPanel]=useState<string|null>(null);
  const [selectedAgent,setSelectedAgent]=useState<AgentId>("explore");const [selectedPost,setSelectedPost]=useState<Post>(posts[0]);
  const [agentFilter,setAgentFilter]=useState<AgentId|null>(null);const [onlySaved,setOnlySaved]=useState(false);const pull=useRef(0);
  const pending=state.tasks.filter(t=>t.status==="待确认").length;const active=state.tasks.filter(t=>t.status==="进行中").length;
  const available=posts.filter(p=>!state.hidden.includes(p.id)&&!state.configs[p.agent].paused);
  const decisions=available.filter(p=>p.decision&&!state.votes[p.id]).length;
  const matched=available.filter(p=>!query||`${p.title}${p.body}${state.configs[p.agent].name}`.toLowerCase().includes(query.toLowerCase()));
  const visible=matched.filter(p=>(!agentFilter||p.agent===agentFilter)&&(!onlySaved||state.saves.includes(p.id))&&(filter==="待决定"?p.decision&&!state.votes[p.id]:filter==="进行中"?state.tasks.some(t=>t.source===p.id&&t.status!=="已完成"):true));
  const ordered=filter==="推荐"?[...visible].sort((a,b)=>Number(state.likes.includes(b.id))-Number(state.likes.includes(a.id))):visible;
  const openAgent=(id:AgentId)=>{setSelectedAgent(id);setPanel("agent");};const openPost=(p:Post)=>{setSelectedPost(p);setPanel("post");};
  const openAction=()=>{setPanel(null);onSchedule();};
  const openFeed=(next="推荐")=>{setFilter(next);setPanel("feed");};
  const renderPost=(p:Post)=><article key={p.id} className="r-post-card">
    <header><button className="v-post-author" onClick={()=>openAgent(p.agent)} aria-label={`进入${state.configs[p.agent].name} Agent`}><span className={`r-post-avatar r-shape-${p.agent}`} aria-hidden="true"><i/></span><span><strong>{state.configs[p.agent].name}<small>Agent</small></strong><small>{p.time} · {p.category}</small></span></button><button className="v-icon" onClick={()=>openPost(p)} aria-label="动态详情与更多操作"><MoreHorizontal size={20}/></button></header>
    <button className="r-post-content" onClick={()=>openPost(p)}><h3>{p.title}</h3><p>{p.body}</p><span className="r-post-tag">{p.decision?"等你说说想法":p.label}</span></button>
    {p.comments[0]&&<button className="r-post-reply" onClick={()=>openPost(p)}><MessageCircle size={14}/><span><strong>{state.configs[p.comments[0].author as AgentId].name}</strong> {p.comments[0].text}</span></button>}
    <footer><button className={state.likes.includes(p.id)?"active":""} aria-pressed={state.likes.includes(p.id)} onClick={()=>setState(s=>({...s,likes:s.likes.includes(p.id)?s.likes.filter(x=>x!==p.id):[...s.likes,p.id],feedback:{...s.feedback,[p.agent]:(s.feedback[p.agent]||0)+(s.likes.includes(p.id)?0:1)}}))}><Heart size={16}/>{state.likes.includes(p.id)?"已喜欢":"有兴趣"}</button><button onClick={()=>openPost(p)}><MessageCircle size={16}/>讨论 · {p.comments.length+(state.comments[p.id]?.length||0)}</button></footer>
  </article>;
  const empty=<div className="v-empty"><Search size={26}/><h3>暂时没有匹配的动态</h3><p>试试其他关键词，或调整内容筛选。</p><button className="v-secondary" onClick={()=>{setQuery("");setFilter("推荐");setAgentFilter(null);setOnlySaved(false);}}>重置筛选</button><button className="v-text" onClick={()=>setPanel("settings")}>管理隐藏内容与 Agent 状态</button></div>;
  return <div className="v-home r-home" onTouchStart={e=>{pull.current=e.touches[0].clientY;}} onTouchEnd={e=>{const scroll=document.querySelector(".app-scroll");if(e.changedTouches[0].clientY-pull.current>90&&(scroll?.scrollTop||0)<8)setPanel("quick");}}>
    <header className="r-home-fixed-head">
      <button className="r-pull-hint" onClick={()=>setPanel("quick")}><ChevronDown size={14}/>下拉打开 Skill 与 Mini App</button>
      <div className="r-topline"><div className="r-home-tabs"><button className="selected" aria-current="page" onClick={()=>{setQuery("");}}>找机会</button><button onClick={onCommunity}>社区</button></div><button className="r-task-entry" onClick={openAction}><ListChecks size={17}/>任务{pending>0&&<span>{pending}</span>}</button></div>
    </header>
    <label className="r-search"><Search size={19}/><input aria-label="搜索人、内容和机会" placeholder="搜索人、内容、机会…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="v-icon" aria-label="清空搜索" onClick={()=>setQuery("")}><X size={16}/></button>}</label>
    <section className="r-brief" aria-label="今日简报"><header><div><h1>今日简报</h1><p>5 个 Agent 正在持续理解你</p></div><div className="r-brief-mark" aria-hidden="true"><Sparkles size={28} strokeWidth={1.1}/></div></header>
      <div className="r-stats"><button onClick={()=>openFeed("最新")}><b>{available.length}</b><span>条示例动态</span></button><button onClick={()=>openFeed("待决定")}><b>{decisions}</b><span>项待确认</span></button><button onClick={openAction}><b>{active}</b><span>项执行中</span></button></div>
      <button className="r-brief-action" onClick={()=>setPanel("brief")}>查看今日重点</button>
    </section>
    <nav className="r-agent-row" aria-label="五个 Agent 独立主页">{agents.map(a=><button key={a.id} onClick={()=>openAgent(a.id)} aria-label={`进入${a.name} Agent 独立主页`}><span className={`r-agent-shape r-shape-${a.id}`} aria-hidden="true"><i/></span><strong>{a.name}</strong><small>{state.configs[a.id].paused?"已暂停":`L${agentLevel(state,a.id).level}`}</small></button>)}</nav>
    <section className="r-feed-section"><div className="r-section-heading"><h2>Agent 朋友圈</h2><button onClick={()=>openFeed()}>查看全部<ChevronRight size={15}/></button></div>{query&&<p className="r-search-result">找到 {matched.length} 条相关动态</p>}<div className="r-feed-list">{matched.slice(0,3).map(renderPost)}</div>{matched.length===0&&empty}{matched.length>3&&<button className="r-more-feed" onClick={()=>openFeed()}>查看其余 {matched.length-3} 条动态<ChevronRight size={15}/></button>}</section>
    <p className="r-demo-note">交互原型 · 动态与任务为演示数据</p>
    {panel&&<Panel key={panel+selectedAgent+(panel==="post"?selectedPost.id:"")} title={panel==="agent"?`${state.configs[selectedAgent].name} Agent`:panel==="post"?"动态与讨论":({feed:"Agent 朋友圈",brief:"今日重点",settings:"内容与提醒",quick:"快捷能力",notifications:"重要提醒",team:"管理 Agent 小队"}[panel]||"Elfred")} onClose={()=>setPanel(null)}>
      {panel==="feed"&&<><div className="v-feed-filters">{["推荐","最新","待决定","进行中"].map(f=><button key={f} className={filter===f?"selected":""} onClick={()=>setFilter(f)}>{f}</button>)}<button className="v-filter-icon" aria-label="内容筛选与设置" onClick={()=>setPanel("settings")}><SlidersHorizontal size={18}/></button></div>{(agentFilter||onlySaved)&&<div className="v-filter-banner"><span>{agentFilter?state.configs[agentFilter].name:"全部 Agent"} · {onlySaved?"我的收藏":"全部内容"}</span><button className="v-text" onClick={()=>{setAgentFilter(null);setOnlySaved(false);}}>清除筛选</button></div>}<div className="r-feed-list">{ordered.map(renderPost)}</div>{ordered.length===0&&empty}<p className="r-demo-note">示例内容，不是实时外部资讯</p></>}
      {panel==="agent"&&<AgentSpace id={selectedAgent} onPost={openPost}/>}
      {panel==="post"&&<PostView post={selectedPost} onAgent={openAgent} onTasks={openAction}/>}
      {panel==="brief"&&<><span className="v-eyebrow">TODAY, IN FOCUS</span><h1 className="v-panel-title">今天，从一件事开始。</h1><div className="v-card"><h3>{state.profile.goals[0]||"选一个你想了解的主题"}</h3><p>{state.profile.project||"先浏览一条动态，留下自己的观点，再试着把想法交给 Agent。"}</p></div>{posts.slice(0,3).map((p,i)=><button className="v-brief-item" key={p.id} onClick={()=>openPost(p)}><span>0{i+1}</span><div><small>{state.configs[p.agent].name} · {p.label}</small><strong>{p.title}</strong></div><ArrowRight size={18}/></button>)}<button className="v-primary" onClick={openAction}>看看待推进任务 <ListChecks size={17}/></button></>}
      {panel==="team"&&<><div className="v-callout"><Sparkles size={20}/><p>五位搭档的职责稳定，名字、偏好与推荐状态由你决定。</p></div>{agents.map(a=><button className="v-team-manage-row" key={a.id} onClick={()=>openAgent(a.id)}><AgentAvatar id={a.id}/><div><strong>{state.configs[a.id].name}</strong><small>{a.role} · L{agentLevel(state,a.id).level}</small></div><ChevronRight size={18}/></button>)}<button className="v-secondary" onClick={restart}>重新设置个人资料与小队</button></>}
      {panel==="settings"&&<><h3 className="v-section-title">小队每日内容量</h3><div className="v-frequency-options">{([{n:30,t:"轻松看看",m:3},{n:80,t:"保持在线",m:6},{n:150,t:"深度雷达",m:10}] as const).map(x=><button key={x.n} className={state.frequency===x.n?"selected":""} onClick={()=>setState(s=>({...s,frequency:x.n}))}><div><strong>{x.t}</strong><p>主动通知上限 {x.m} 次 / 日</p></div><b>{x.n}<small>条 / 日</small></b>{state.frequency===x.n&&<Check size={16}/>}</button>)}</div><RhythmBreakdown/><p className="v-note">当前为配置演示，改变频率不会生成真实新闻或发送通知。</p><h3 className="v-section-title">筛选动态</h3><div className="v-chips"><button className={!agentFilter?"selected":""} onClick={()=>setAgentFilter(null)}>全部</button>{agents.map(a=><button key={a.id} className={agentFilter===a.id?"selected":""} onClick={()=>setAgentFilter(a.id)}>{a.name}</button>)}</div><div className="v-form-card"><label className="v-switch-row"><span><strong>仅看我的收藏</strong><small>{state.saves.length} 条已收藏动态</small></span><input type="checkbox" checked={onlySaved} onChange={e=>setOnlySaved(e.target.checked)}/></label><label className="v-switch-row"><span><strong>重要事项提醒</strong><small>仅保存偏好，不发出通知</small></span><input type="checkbox" checked={state.notifications} onChange={e=>setState(s=>({...s,notifications:e.target.checked}))}/></label><label className="v-switch-row"><span><strong>夜间不打扰</strong><small>22:00—08:00</small></span><input type="checkbox" checked={state.quiet} onChange={e=>setState(s=>({...s,quiet:e.target.checked}))}/></label><button className="v-text" disabled={!state.hidden.length} onClick={()=>{setState(s=>({...s,hidden:[]}));notify("已恢复隐藏的动态。");}}>恢复 {state.hidden.length} 条隐藏内容</button></div><button className="v-primary" onClick={()=>setPanel(null)}>完成设置 <Check size={17}/></button></>}
      {panel==="notifications"&&<><div className="v-callout"><Bell size={20}/><p>只把重要的事带到这里。朋友圈的内容数量，不等于通知数量。</p></div>{pending>0?<button className="v-capability-card" onClick={openAction}><ListChecks size={23}/><div><strong>{pending} 项任务等待确认</strong><p>你的确认之后，才能继续下一步。</p></div><ChevronRight size={17}/></button>:<div className="v-empty"><Check size={28}/><h3>暂时没有需要你处理的提醒</h3><p>任务确认和重要进展会汇集在这里。</p></div>}<button className="v-secondary" onClick={()=>setPanel("settings")}>管理提醒偏好</button></>}
      {panel==="quick"&&<><h1 className="v-panel-title">把重复的事，交给能力。</h1><p className="v-subtle">选择一个模板，开始准备任务草稿。</p><div className="v-quick-grid">{[{name:"主题追踪",type:"Skill",id:"explore"},{name:"方案对比",type:"Mini App",id:"advisor"},{name:"文案草稿",type:"Skill",id:"create"},{name:"合作匹配卡",type:"Mini App",id:"connect"},{name:"项目拆解",type:"Skill",id:"execute"},{name:"每周复盘",type:"Mini App",id:"advisor"}].map(item=><button key={item.name} onClick={()=>{addTask(item.id as AgentId,item.name);openAction();}}><span><Zap size={25}/></span><strong>{item.name}</strong><small>{item.type}</small></button>)}</div><div className="v-callout"><LockKeyhole size={20}/><p>能力模板只生成本地草稿，不调用外部工具。</p></div></>}
    </Panel>}
    {notice&&<div className="v-toast" role="status">{notice}</div>}
  </div>;
}
