import test from 'node:test';
import assert from 'node:assert/strict';
import {Store,id} from '../../server/elfred/store.mjs';
import {Service} from '../../server/elfred/service.mjs';
import {Runtime} from '../../server/elfred/runtime.mjs';
import {authenticate} from '../../server/elfred/auth.mjs';
test('真人验收触发唯一私人主帖，协作与后续追问归入讨论，社区无AI帖',async t=>{
 const store=new Store(':memory:');t.after(()=>store.close());const calls=[],provider={status:()=>({configured:true}),generate:async p=>{calls.push(p);return {output:p.goal.phase==='collaboration'?'协作证据：需要补充样本':'可审核的本人成果',usage:{total_tokens:2}}}},service=new Service(store,provider),runtime=new Runtime(store,provider),a=authenticate(store,'feed-test-a','test-password-long',true,'甲').user,b=authenticate(store,'feed-test-b','test-password-long',true,'乙').user;service.initialize(a);service.initialize(b);const cmd=(action,input)=>service.command(a.id,id(),action,input),ref=o=>({id:o.id,version:store.get(o.id).version});
 const task=cmd('task.create',{goal:'整理发现并写成说明',system:'create',review_mode:'single'});cmd('task.collaboration',{...ref(task),confirm:true,steps:[{id:'evidence',system:'explore',goal:'找出证据缺口',source_refs:[],depends:[]}]});const execute=async task=>{cmd('task.confirm',{...ref(task),confirm:true,model_consent:true});cmd('run.start',ref(task));await runtime.tick();cmd('task.accept',{...ref(task),accept:true})};await execute(task);const feed=store.visible(a.id,'feed')[0];assert.equal(feed.data.comments.length,1);assert.equal(feed.data.comments[0].system,'explore');assert.match(feed.data.comments[0].content,/补充样本/);assert.equal(store.visible(b.id,'feed').length,0);
 const followup=cmd('feed.question',{...ref(feed),goal:'补充不同角度',system:'advise'});assert.equal(store.list('feed').length,1);await execute(followup);assert.match(JSON.stringify(calls.at(-1).context),/可审核的本人成果/);assert.match(JSON.stringify(calls.at(-1).context),/补充样本/);assert.equal(store.list('feed').length,1);const reply=store.visible(a.id,'feedback').find(f=>f.data.kind==='agent_response');assert.equal(reply.data.feed_id,feed.id);assert.equal(reply.data.system,'advise');assert.equal(store.visible(b.id,'feedback').length,0);assert.equal(store.list('post').length,0);assert.equal(store.list('memory').length,0);
 cmd('feed.feedback',{...ref(feed),kind:'content_error',note:'样本范围应重新核对'});assert.equal(store.list('memory').length,0);
 const post=cmd('post.create',{title:'真人公开成果',content:'仅公开已确认文字',confirm:true}),follow=()=>service.command(b.id,id(),'post.follow_author',{id:post.id});follow();assert.equal(store.visible(b.id,'interaction').find(i=>i.data.kind==='follow_author').data.object_id,a.id);assert.equal(store.visible(a.id,'interaction').length,0);follow();assert.equal(store.visible(b.id,'interaction')[0].data.active,false);assert.throws(()=>cmd('post.follow_author',{id:post.id}),{code:'INVALID_INPUT'});
});
