import test from 'node:test';
import assert from 'node:assert/strict';
import {Store,id} from '../../server/elfred/store.mjs';
import {Service} from '../../server/elfred/service.mjs';
import {authenticate} from '../../server/elfred/auth.mjs';
import {projectProgress} from '../../server/elfred/project-progress.mjs';
test('共创看板只给成员必要状态；上游更新阻止旧依据提交，重新选择后恢复',t=>{
 const store=new Store(':memory:');t.after(()=>store.close());const service=new Service(store,{status:()=>({configured:false})}),users=['board-a','board-b','board-c'].map(h=>authenticate(store,h,'board-test-password',true,h).user);users.forEach(u=>service.initialize(u));const [a,b,c]=users,cmd=(u,action,input)=>service.command(u.id,id(),action,input),ref=o=>({id:o.id,version:store.get(o.id).version});
 const p=cmd(a,'project.create',{title:'共创作品',goal:'合作完成',criteria:'核对结果',task:'共同工作'}),up=cmd(a,'project.slot.save',{project_id:p.id,title:'上游',criteria:'可读',capacity:null}),down=cmd(a,'project.slot.save',{project_id:p.id,title:'下游',criteria:'可读',capacity:null,depends_on:[up.id]}),post=cmd(a,'project.publish_post',{...ref(p),confirm:true});
 cmd(b,'project.claim',{post_id:post.id,slot_id:down.id,slot_version:store.get(down.id).version,confirm:true});const source=cmd(a,'copy.create',{project_id:p.id,slot_id:up.id}),target=cmd(b,'copy.create',{project_id:p.id,slot_id:down.id});cmd(a,'copy.save',{...ref(source),content:'接口一'});cmd(b,'copy.save',{...ref(target),content:'下游草稿PRIVATE_COPY'});const stage=cmd(a,'copy.stage',{...ref(source),title:'接口阶段',reviewed:true});cmd(b,'stage.depend',{...ref(target),stage_id:stage.id});const task=cmd(b,'copy.ai_prepare',{...ref(target),goal:'PRIVATE_INSTRUCTION',confirm:true,model_consent:true});
 const rows=projectProgress(store,a.id,store.get(p.id));assert.equal(rows.find(r=>r.id===down.id).participants[0].status,'draft');assert.doesNotMatch(JSON.stringify(rows),/PRIVATE_COPY|PRIVATE_INSTRUCTION/);assert.deepEqual(projectProgress(store,c.id,store.get(p.id)),[]);
 const middle=cmd(b,'copy.stage',{...ref(target),title:'引用上游的中间阶段',reviewed:true});cmd(c,'project.claim',{post_id:post.id,slot_id:down.id,slot_version:store.get(down.id).version,confirm:true});const third=cmd(c,'copy.create',{project_id:p.id,slot_id:down.id});cmd(c,'copy.save',{...ref(third),content:'引用中间阶段的正文'});cmd(c,'stage.depend',{...ref(third),stage_id:middle.id});
 cmd(a,'copy.save',{...ref(source),content:'接口二'});const newer=cmd(a,'copy.stage',{...ref(source),title:'新接口阶段',reviewed:true});assert.equal(projectProgress(store,a.id,store.get(p.id)).find(r=>r.id===down.id).participants[0].status,'dependency_changed');assert.throws(()=>cmd(b,'copy.submit',{...ref(target),reviewed:true}));assert.throws(()=>cmd(b,'task.confirm',{...ref(task),confirm:true,model_consent:true}));
 assert.throws(()=>cmd(c,'copy.submit',{...ref(third),reviewed:true}));assert.equal(projectProgress(store,a.id,store.get(p.id)).find(r=>r.id===down.id).participants.find(p=>p.id===c.id).status,'dependency_changed');const revised=cmd(b,'copy.revise',ref(target));assert.equal(store.get(revised.id).data.stage_refs[0].id,stage.id);assert.throws(()=>cmd(b,'copy.submit',{...ref(revised),reviewed:true}));
 cmd(b,'stage.depend',{...ref(target),stage_id:newer.id});assert.equal(store.get(target.id).data.stage_refs.length,1);const submitted=cmd(b,'copy.submit',{...ref(target),reviewed:true});assert.equal(store.get(submitted.id).data.status,'submitted');assert.match(projectProgress(store,a.id,store.get(p.id)).find(r=>r.id===down.id).needs_decision,/发起者审核提交/);
});
