import test from 'node:test';
import assert from 'node:assert/strict';
import {Store,id} from '../../server/elfred/store.mjs';
import {Service} from '../../server/elfred/service.mjs';
import {Runtime} from '../../server/elfred/runtime.mjs';
import {authenticate} from '../../server/elfred/auth.mjs';
import {semanticPreview,semanticResults} from '../../server/elfred/semantic-search.mjs';
import {searchJudgment} from '../../server/elfred/search-commands.mjs';
import {EmbeddingProvider} from '../../server/elfred/embedding-provider.mjs';
function setup(t){const store=new Store(':memory:');t.after(()=>store.close());const calls=[],provider={status:()=>({embedding:'configured',configured:true}),embed:async i=>{calls.push(i);return {vectors:i.input.map((text,index)=>index===0||text.includes('车辆')?[1,0]:[0,1]),usage:{total_tokens:20},model:'test-only-vector'}},generate:async()=>({output:'{"results":[]}',usage:{total_tokens:2}})},service=new Service(store,provider),runtime=new Runtime(store,provider),a=authenticate(store,'vector-a','vector-test-password',true,'甲').user,b=authenticate(store,'vector-b','vector-test-password',true,'乙').user;[a,b].forEach(u=>service.initialize(u));const cmd=(action,input)=>service.command(a.id,id(),action,input),ref=o=>({id:o.id,version:store.get(o.id).version});return {store,calls,service,runtime,a,b,cmd,ref};}
test('向量召回找出零共同关键词对象，RRF保留关键词独有结果且权限过滤发生在调用前',async t=>{
 const {store,calls,runtime,a,b,cmd}=setup(t);const semantic=cmd('knowledge.create',{title:'园区制度',content:'禁止车辆驶入步行街'}),keyword=cmd('knowledge.create',{title:'机动车登记',content:'登记说明'});store.add('knowledge',b.id,{title:'PRIVATE_OTHER_TITLE',content:'PRIVATE_OTHER_CONTENT'});const input={query:'机动车通行规则',types:['knowledge']},preview=semanticPreview(store,a.id,input);assert.equal(preview.chunks.length,2);assert.doesNotMatch(JSON.stringify(preview),/PRIVATE_OTHER/);
 const task=cmd('search.semantic',{...input,plan_key:preview.plan_key,confirm:true,model_consent:true});await runtime.tick();assert.equal(calls.length,1);assert.doesNotMatch(JSON.stringify(calls),/PRIVATE_OTHER/);const result=semanticResults(store,a.id,{...input,semantic_task_id:task.id});assert.ok(result.hits.some(h=>h.id===semantic.id&&h.channels.includes('vector')));assert.ok(result.hits.some(h=>h.id===keyword.id&&h.channels.includes('keyword')));assert.ok(result.hits.every(h=>h.condition_status==='unknown'));assert.equal(result.coverage.status,'complete');
 const judged=cmd('search.judge',{...input,semantic_task_id:task.id,query_id:result.query_id,candidates:result.hits.map(h=>({id:h.id,version:h.version})),confirm:true,model_consent:true});await runtime.tick();assert.ok(searchJudgment(store,a.id,{...input,semantic_task_id:task.id,task_id:judged.id}).hits.some(h=>h.id===semantic.id));
});
test('语义范围版本变更、撤权和条件变化均不能沿旧结果继续使用',async t=>{
 const {store,runtime,a,cmd,ref}=setup(t),note=cmd('knowledge.create',{title:'园区制度',content:'禁止车辆驶入'}),input={query:'机动车',types:['knowledge']},preview=semanticPreview(store,a.id,input);cmd('knowledge.update',{...ref(note),title:'新制度',content:'步行区仅可步行'});assert.throws(()=>cmd('search.semantic',{...input,plan_key:preview.plan_key,confirm:true,model_consent:true}),{code:'SEARCH_SCOPE_CHANGED'});
 const current=semanticPreview(store,a.id,input),task=cmd('search.semantic',{...input,plan_key:current.plan_key,confirm:true,model_consent:true});await runtime.tick();assert.throws(()=>semanticResults(store,a.id,{query:'完全不同',types:['knowledge'],semantic_task_id:task.id}),{code:'QUERY_CHANGED'});cmd('knowledge.update',{...ref(note),title:'再更新',content:'新正文'});assert.throws(()=>semanticResults(store,a.id,{...input,semantic_task_id:task.id}),{code:'NOT_FOUND'});
});
test('语义多批次失败保留覆盖范围，恢复不重复已完成调用；没有Key零调用零费用',async t=>{
 const {store,calls,runtime,a,cmd,ref}=setup(t);for(let i=0;i<12;i++)cmd('knowledge.create',{title:'资料'+i,content:'车辆管理'+i});const input={query:'通行',types:['knowledge']},preview=semanticPreview(store,a.id,input);let enabled=false;runtime.provider.status=()=>({embedding:enabled?'configured':'not_configured',configured:false});const task=cmd('search.semantic',{...input,plan_key:preview.plan_key,confirm:true,model_consent:true});await runtime.tick();assert.equal(calls.length,0);assert.equal(store.get(task.id).data.units,0);
 enabled=true;const embed=runtime.provider.embed;runtime.provider.embed=async i=>{const result=await embed(i);enabled=false;return result;};cmd('run.start',ref(task));await runtime.tick();assert.equal(calls.length,1);const partial=semanticResults(store,a.id,{...input,semantic_task_id:task.id});assert.equal(partial.coverage.processed_chunks,10);assert.equal(partial.coverage.status,'partial');enabled=true;runtime.provider.embed=embed;cmd('run.start',ref(task));await runtime.tick();assert.equal(calls.length,2);assert.equal(semanticResults(store,a.id,{...input,semantic_task_id:task.id}).coverage.processed_chunks,12);
});
test('向量适配器请求官方结构，拒绝未知用量、错序和零向量',async()=>{
 let payload;const provider=new EmbeddingProvider({OPENAI_API_KEY:'test-only-not-a-real-key'},async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/embeddings');payload=JSON.parse(options.body);return {ok:true,text:async()=>JSON.stringify({data:[{index:1,embedding:[0,1]},{index:0,embedding:[1,0]}],usage:{total_tokens:2}})};});const result=await provider.embed({input:['问题','材料'],maxTokens:1000});assert.equal(payload.encoding_format,'float');assert.deepEqual(result.vectors[0],[1,0]);assert.doesNotMatch(JSON.stringify(provider.status()),/test-only/);
 for(const data of [{data:[{index:0,embedding:[1]}]}, {data:[{index:0,embedding:[0]}],usage:{total_tokens:1}},{data:[{index:1,embedding:[1]}],usage:{total_tokens:1}}]){const p=new EmbeddingProvider({OPENAI_API_KEY:'test'},async()=>({ok:true,text:async()=>JSON.stringify(data)}));await assert.rejects(p.embed({input:['文字'],maxTokens:1000}));}
});
test('超过四十片段时后续批次合并前批候选，范围变化不能跳页',async t=>{
 const {store,runtime,a,cmd}=setup(t);for(let i=0;i<45;i++)cmd('knowledge.create',{title:'材料'+i,content:'车辆管理'+i});const input={query:'通行',types:['knowledge']},first=semanticPreview(store,a.id,input),one=cmd('search.semantic',{...input,plan_key:first.plan_key,confirm:true,model_consent:true});await runtime.tick();
 const second=semanticPreview(store,a.id,{...input,semantic_offset:first.next_offset}),two=cmd('search.semantic',{...input,semantic_offset:second.offset,semantic_previous_id:one.id,plan_key:second.plan_key,confirm:true,model_consent:true});await runtime.tick();const result=semanticResults(store,a.id,{...input,semantic_task_id:two.id});assert.equal(result.coverage.accumulated_chunks,45);assert.equal(result.hits.length,45);assert.equal(result.coverage.next_offset,null);
 cmd('knowledge.create',{title:'新增材料',content:'车辆相关'});const changed=semanticPreview(store,a.id,{...input,semantic_offset:40});assert.throws(()=>cmd('search.semantic',{...input,semantic_offset:40,semantic_previous_id:one.id,plan_key:changed.plan_key,confirm:true,model_consent:true}),{code:'SEARCH_SCOPE_CHANGED'});
});
test('只查最新版排除明确旧版，并可沿符合时间的消息召回原文件',t=>{
 const {store,a,cmd}=setup(t),old=store.add('knowledge',a.id,{title:'旧版',content:'车辆旧制度',is_current:false}),current=cmd('knowledge.create',{title:'新制度',content:'车辆规则'}),latest=semanticPreview(store,a.id,{query:'通行',types:['knowledge'],latest:true});assert.ok(!latest.chunks.some(c=>c.id===old.id));assert.ok(latest.chunks.some(c=>c.id===current.id));
 const attachment=store.add('document',a.id,{title:'历史附件',content:'车辆说明'});store.db.prepare('UPDATE objects SET created=? WHERE id=?').run('2020-01-01T00:00:00Z',attachment.id);const message=store.add('message',a.id,{content:'请查看随附资料',attachments:[{id:attachment.id,version:attachment.version}]});const scope=semanticPreview(store,a.id,{query:'通行',types:['message','document'],after:'2025-01-01T00:00:00Z'});assert.ok(scope.chunks.some(c=>c.id===attachment.id&&c.origin_id===message.id));
});
test('空白片段不进入模型，发布版本切换后旧向量不再参加最新结果',async t=>{
 const {store,a,cmd,runtime,calls}=setup(t);cmd('document.create',{title:'空白.md',content:'begin'+' '.repeat(4000)+'end'});const project=store.add('project',a.id,{title:'作品',status:'active'}),old=store.add('release',a.id,{title:'旧发布',content:'车辆规则',project_id:project.id,status:'published'}),next=store.add('release',a.id,{title:'新发布',content:'车辆新规则',project_id:project.id,status:'published'});store.update(project,{...project.data,release_id:old.id},a.id);
 const input={query:'通行',types:['document','release'],latest:true},scope=semanticPreview(store,a.id,input),task=cmd('search.semantic',{...input,plan_key:scope.plan_key,confirm:true,model_consent:true});await runtime.tick();assert.ok(calls[0].input.every(s=>s.trim()));assert.ok(semanticResults(store,a.id,{...input,semantic_task_id:task.id}).hits.some(h=>h.id===old.id));store.update(store.get(project.id),{...store.get(project.id).data,release_id:next.id},a.id);assert.ok(!semanticResults(store,a.id,{...input,semantic_task_id:task.id}).hits.some(h=>h.id===old.id&&h.channels.includes('vector')));
});
