"use client";
import {FollowAuthor} from './community-author';
import {useState} from 'react';
import {useRuntime,entityRef} from '../../core/runtime-context';
import {Action,Field} from '../../core/runtime-panels';
import {ArtifactPreview} from './project-slots';
import {type Entity,text} from '../live/types';
import type {Screen} from '../../core/screen';
type Go=(screen:Screen)=>void;
export function CommunityWorkCard({release,go}:{release:Entity;go:Go}){
 const runtime=useRuntime()!,saved=runtime.snapshot!.objects.interaction.some(i=>i.data.object_id===release.id&&i.data.kind==='save'&&i.data.active);
 return <article className="v277-social-post"><header><i className="community-human-avatar">{(text(release,'author_name')||'作').slice(0,1)}</i><span><b>{text(release,'author_name')||'真人发布的作品'}</b><small>{new Date(release.created).toLocaleDateString('zh-CN')} · 版本 {String(release.data.revision)}</small></span></header><button className="v277-social-body" onClick={()=>go({name:'community-post',id:release.id})}><span className="community-cocreation-label">作品</span><h3>{text(release,'title')}</h3><p>{text(release,'purpose')||text(release,'content').slice(0,160)}</p><p>{release.data.format==='web'?'打开后运行交互预览':'打开查看已发布成果'} ›</p></button><small>{text(release,'tool_description')||'此版本未记录工具说明'}</small><div className="elfred-inline-actions"><button onClick={()=>go({name:'community-post',id:release.id})}>体验与讨论</button><Action run={()=>runtime.command('post.interact',{id:release.id,kind:'save'})}>{saved?'取消收藏':'收藏作品'}</Action>{release.data.license==='copy-with-attribution'&&<button onClick={()=>go({name:'community-post',id:release.id})}>复制并创作</button>}</div></article>;
}
export function ReleaseDetail({release,go,onBack}:{release:Entity;go:Go;onBack:()=>void}){
 const runtime=useRuntime()!,s=runtime.snapshot!,[comment,setComment]=useState(''),[goal,setGoal]=useState('');
 const post=s.objects.post.find(p=>p.data.project_id===release.data.project_id),source=s.objects.release.find(r=>r.id===release.data.origin_release);
 return <main className="v277-page v278-social-detail"><header className="v277-page-head"><button onClick={onBack}>返回</button><h1>{text(release,'title')}</h1></header><section className="v277-edit-card"><ArtifactPreview item={release}/>{release.data.format!=='web'&&<p style={{whiteSpace:'pre-wrap'}}>{text(release,'content')}</p>}<FollowAuthor post={release}/><h2>用途与说明</h2><p>{text(release,'purpose')||'发布者尚未补充用途说明'}</p><p>版本 {String(release.data.revision)} · {new Date(release.created).toLocaleString('zh-CN')}{release.data.is_current?' · 当前发布版':' · 历史版本'}</p><p>真人发布者：{text(release,'author_name')||'历史版本未记录姓名'}</p><p>贡献者：{((release.data.contributors||[]) as {name:string}[]).map(c=>c.name).join('、')||'历史版本未记录完整名单'}</p><p>{text(release,'tool_description')||'历史版本未记录工具说明'}</p>{source&&<button onClick={()=>go({name:'community-post',id:source.id})}>查看原作品及署名</button>}{post&&<button onClick={()=>go({name:'community-post',id:post.id})}>查看项目及开放任务</button>}<details><summary>发布文件与版本</summary>{Object.keys((release.data.files||{}) as object).map(path=><p key={path}>{path}</p>)}{s.objects.release.filter(r=>r.data.project_id===release.data.project_id&&r.id!==release.id).map(r=><button key={r.id} onClick={()=>go({name:'community-post',id:r.id})}>版本 {String(r.data.revision)}{r.data.is_current?' · 当前':''}</button>)}</details></section>{release.data.license==='copy-with-attribution'&&<section className="v277-edit-card"><Field name="独立再创作目标" value={goal} onChange={setGoal}/><Action disabled={!goal.trim()} run={async()=>{const r=await runtime.command('project.fork',{release_id:release.id,goal});go({name:'community-post',id:r.id})}}>保留原作者署名，创建本人私有副本</Action></section>}<section className="v277-edit-card"><h3>作品讨论</h3>{s.objects.comment.filter(c=>c.data.post_id===release.id).map(c=><article key={c.id}><b>{text(c,'author_name')}</b><p>{text(c,'content')}</p></article>)}<Field name="评论作品" area value={comment} onChange={setComment}/><Action disabled={!comment.trim()} run={async()=>{await runtime.command('post.comment',{id:release.id,content:comment});setComment('')}}>确认发表本人评论</Action></section></main>;
}
