"use client";
import {useEffect,useState} from 'react';
import {ExternalTool} from './external-tools';
import {SemanticSearch,type SemanticResult} from './semantic-search';
import {Search,X} from 'lucide-react';
import {useRuntime,entityRef} from '../../core/runtime-context';
import {RootPortal} from '../../legacy/legacy-ui';
import {Action,Field} from '../../core/runtime-panels';
import {VoiceInput} from '../messages/voice-input';
import {AttachmentPicker,type FileRef} from '../live/attachments';
import {objectScreen} from '../../core/object-screen';
import {type Entity,text,statuses} from '../live/types';
import type {Screen} from '../../core/screen';
type Hit={id:string;version:number;type:string;title:string;excerpt:string;anchor:string;origin_id?:string;condition_status:string;condition_checks:{condition:string;status:string;evidence:string}[]};
type SearchResult={status:string;query_id:string;hits:Hit[];intent:{terms:string[];conditions:string[];uncertainties:string[];interpretation?:string[];after?:string;before?:string}};
export function ConnectedSearch({go,onClose}:{go:(screen:Screen)=>void;onClose:()=>void}){
 const runtime=useRuntime()!,s=runtime.snapshot!;
 const storageKey='elfred-search-input:'+s.user.id;
 const [restored]=useState<Record<string,string|boolean>>(()=>{try{return JSON.parse(sessionStorage.getItem(storageKey)||'{}')}catch{return {}}});
 const [query,setQuery]=useState(String(restored.query||'')),[space,setSpace]=useState(String(restored.space||'')),[author,setAuthor]=useState(String(restored.author||'')),[kind,setKind]=useState(String(restored.kind||'')),[conditions,setConditions]=useState(String(restored.conditions||'')),[exclude,setExclude]=useState(String(restored.exclude||'')),[after,setAfter]=useState(String(restored.after||'')),[before,setBefore]=useState(String(restored.before||'')),[latest,setLatest]=useState(restored.latest===true),[result,setResult]=useState<SearchResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[files,setFiles]=useState<FileRef[]>([]),[inputText,setInputText]=useState(''),[consent,setConsent]=useState(false),[judgeProvider,setJudgeProvider]=useState('text'),[judgeTask,setJudgeTask]=useState(''),[parseTask,setParseTask]=useState(''),[judgment,setJudgment]=useState<{hits:Hit[]}|null>(null);
 const input={query,space:space||undefined,author:author||undefined,types:kind?[kind]:undefined,conditions:conditions.split('\n').map(c=>c.trim()).filter(Boolean),exclude:exclude.split(/[,，]/).map(c=>c.trim()).filter(Boolean),after:after?new Date(after).toISOString():undefined,before:before?new Date(before).toISOString():undefined,latest:latest||undefined};
 const key=JSON.stringify(input);
 const [semantic,setSemantic]=useState<SemanticResult|null>(null),[semanticId,setSemanticId]=useState('');
 useEffect(()=>{try{sessionStorage.setItem(storageKey,JSON.stringify({query,space,author,kind,conditions,exclude,after,before,latest}))}catch{}},[storageKey,key,kind,conditions,exclude]);
 useEffect(()=>{setSemantic(null);setSemanticId('');setResult(null);setJudgment(null);setJudgeTask('');setError('');if(!query.trim()){setBusy(false);return;}let active=true;setBusy(true);const timer=setTimeout(()=>{void runtime.request<SearchResult>('/search',JSON.parse(key)).then(r=>{if(active)setResult(r)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)})},250);return()=>{active=false;clearTimeout(timer)}},[key,retry]);
 const task=s.objects.task.find(t=>t.id===judgeTask),run=s.objects.run.find(r=>r.id===task?.data.run_id);
 useEffect(()=>{if(!judgeTask||!run||!['completed','awaiting_review'].includes(text(run,'status')))return;let active=true;void runtime.request<{hits:Hit[]}>('/search-judgment',{task_id:judgeTask,...JSON.parse(key),semantic_task_id:semanticId||undefined}).then(r=>{if(active)setJudgment(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[judgeTask,run?.version,key]);
 const parsedTask=s.objects.task.find(t=>t.id===parseTask),parsedRun=s.objects.run.find(r=>r.id===parsedTask?.data.run_id),parsed=(parsedRun?.data.receipts||[]) as {output?:unknown;phase?:string}[];
 const parsedText=[...parsed].reverse().find(r=>typeof r.output==='string'&&r.phase!=='review')?.output;
 const start=async(id:string)=>{const draft=await runtime.request<Entity>('/objects/'+id);await runtime.command('task.confirm',{...entityRef(draft),confirm:true,model_consent:true});const ready=await runtime.request<Entity>('/objects/'+id);await runtime.command('run.start',entityRef(ready))};
 const cachedHits=judgment?.hits||semantic?.hits||result?.hits||[];
 const currentObjects=new Map(Object.values(s.objects).flat().map(o=>[o.id,o]));
 const changed=cachedHits.some(h=>currentObjects.get(h.id)?.version!==h.version);
 const hits=cachedHits.filter(h=>currentObjects.get(h.id)?.version===h.version);
 useEffect(()=>{if(changed)setRetry(v=>v+1)},[changed]);
 const open=async(hit:Hit)=>{try{const object=await runtime.request<Entity>('/objects/'+hit.id);if(object.version!==hit.version){setRetry(v=>v+1);runtime.report('来源版本已更新，已重新检索，请核对新版本');return;}go(objectScreen(object,hit.excerpt.split("\n")[0]));}catch(e){setResult(prev=>prev?{...prev,hits:prev.hits.filter(h=>h.id!==hit.id)}:prev);setJudgment(null);setError(e instanceof Error?e.message:'来源已不可访问')}};
 return <RootPortal><button className="v278-sheet-backdrop elfred-search-backdrop" aria-label="关闭全局搜索" onClick={onClose}/><section className="v278-half-sheet v278-global-search-page elfred-connected-search" role="dialog" aria-modal="true" aria-label="全局搜索"><header className="v278-sheet-header"><span><h2>全局搜索</h2><p>找回有权访问的人、资料、任务和成果</p></span><button aria-label="关闭" onClick={onClose}><X size={21}/></button></header><label className="v278-global-search-box"><Search size={22}/><input autoFocus aria-label="全局搜索" placeholder="描述你想找的内容…" value={query} onChange={e=>setQuery(e.target.value)}/><VoiceInput onText={setInputText}/></label>
 <details><summary>修改搜索范围与条件</summary><label className="v277-field">对象类型<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">全部可读对象</option>{[['document','文件'],['knowledge','成果与笔记'],['message','消息'],['conversation','人和群'],['task','任务'],['feed','私人动态'],['inbox','收件箱'],['post','社区帖'],['project','共创项目'],['skill','工具'],['memory','本人理解'],['profile','公开资料']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="v277-field">所在会话<select value={space} onChange={e=>{setSpace(e.target.value);setAuthor('')}}><option value="">全部授权范围</option>{s.objects.conversation.map(c=><option key={c.id} value={c.id}>{text(c,'title')}</option>)}</select></label><label className="v277-field">发送者<select value={author} onChange={e=>setAuthor(e.target.value)}><option value="">不限发送者</option>{[...new Map(s.objects.conversation.filter(c=>!space||c.id===space).flatMap(c=>c.members||[]).map(m=>[m.id,m])).values()].map(m=><option key={m.id} value={m.id}>{m.name} · @{m.handle}</option>)}</select></label><Field name="开始时间（消息发送时间）" type="datetime-local" value={after} onChange={setAfter}/><Field name="结束时间（不含）" type="datetime-local" value={before} onChange={setBefore}/><Field name="必须核对的条件，每行一条" area value={conditions} onChange={setConditions}/><Field name="排除关键词，用逗号分开" value={exclude} onChange={setExclude}/><label><input type="checkbox" checked={latest} onChange={e=>setLatest(e.target.checked)}/>只要最新有效版本，无法确认的列为待核对</label></details>
 <details><summary>用截图、文件或语音补充查询</summary><AttachmentPicker value={files} onChange={setFiles}/>{files.map(file=><div key={file.id}><Action run={async()=>{if(/^(image|audio)\//.test(file.mime)){if(!consent){runtime.report('请先同意本次识别调用');return;}const r=await runtime.command('attachment.analyze',{id:file.id});setParseTask(r.id);await start(r.id)}else{const r=await runtime.request<{text:string}>('/search-input',{id:file.id});setInputText(r.text.slice(0,300))}}}>解析 {file.name}</Action></div>)}<label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意识别本次图片或语音，使用已配置服务和本人额度</label>{parsedTask&&<p>{statuses[text(parsedTask,'status')]}</p>}{typeof parsedText==='string'&&<button onClick={()=>setInputText(parsedText.slice(0,300))}>核对识别出的文字</button>}</details>
 {inputText&&<section className="v277-edit-card"><Field name="核对后作为查询输入" area value={inputText} onChange={setInputText}/><button onClick={()=>{setQuery(inputText.slice(0,300));setInputText('')}}>使用这段文字检索</button><p>查询附件不会自动保存为长期知识。</p></section>}
 {busy&&<p role="status">正在按当前条件检索…</p>}{error&&<section role="alert"><p>{error}</p><button onClick={()=>setRetry(v=>v+1)}>按原条件重试</button></section>}{result&&<p>{['本次检索词：'+result.intent.terms.join('、'),result.intent.interpretation?.join('；'),result.intent.after&&`起 ${result.intent.after}`,result.intent.before&&`止 ${result.intent.before}（不含）`,result.intent.uncertainties.join('；')].filter(Boolean).join('；')}。</p>}
 {result?.status==='complete'&&<><ExternalTool operation="web_search" goal={query} go={go}/><SemanticSearch key={key} input={input} go={go} onResults={(result,id)=>{setSemantic(result);setSemanticId(id);setJudgment(null);setJudgeTask('')}}/><details><summary>核对完整含义与条件</summary><p>基础结果按词义扩展和来源关系召回。下面的核对会把本次问题及可读候选交给所选服务（文字模型最多 20 项，Jev 最多 5 项），预留 1000 本地调用额度；结果仍保留证据和未知项。</p><label className="v277-field">核对服务<select value={judgeProvider} disabled={Boolean(judgeTask)} onChange={e=>setJudgeProvider(e.target.value)}><option value="text">文字模型{s.provider.configured?'':' · 未配置'}</option><option value="jev">Jev 结构化判断{s.provider.jev==='configured'?'':' · 未配置'}</option></select></label><Action disabled={!hits.length||Boolean(judgeTask)} run={async()=>{const r=await runtime.command('search.judge',{...input,provider:judgeProvider,semantic_task_id:semanticId||undefined,query_id:result.query_id,candidates:hits.slice(0,judgeProvider==='jev'?5:20).map(h=>({id:h.id,version:h.version})),confirm:true,model_consent:true});setJudgeTask(r.task_id||r.id)}}>确认核对本次候选</Action>{task&&<p>{statuses[text(task,'status')]} <button onClick={()=>go({name:'task',id:task.id})}>查看运行或停止</button></p>}</details>{!hits.length&&!error&&<p className="v277-empty">当前授权范围和条件下没有结果。可修改条件后重新检索。</p>}{['satisfied','unknown','unsatisfied'].map(status=>{const group=hits.filter(h=>h.condition_status===status);return group.length?<section key={status} className="v278-global-results"><h3>{status==='satisfied'?'符合已核对条件':status==='unknown'?'可能相关，仍待核对':'不满足条件'} · {group.length}</h3>{group.map(hit=><article key={hit.id} style={{padding:'14px 0',borderBottom:'1px solid #e5e9eb'}}><button onClick={()=>void open(hit)}><b>{hit.title}</b><p style={{whiteSpace:'pre-wrap'}}>{hit.excerpt}</p><small>{hit.type} · v{hit.version} · {hit.anchor}</small></button>{hit.condition_checks.map((c,i)=><p key={i}>{c.condition}：{c.status==='satisfied'?'有证据':c.status==='unsatisfied'?'不满足':'未知'} {c.evidence}</p>)}<div><Action run={()=>runtime.command('inbox.create',{object_id:hit.id})}>存入收件箱</Action><Action run={async()=>{const object=await runtime.request<Entity>('/objects/'+hit.id);if(object.version!==hit.version)throw new Error('来源已变化，请重新检索');const r=await runtime.command('task.create',{goal:'依据资料继续处理：'+query,system:'explore',source_refs:[entityRef(object)]});go({name:'task',id:r.id})}}>交给本人 Agent 的草稿</Action>{hit.origin_id&&<button onClick={()=>void runtime.request<Entity>('/objects/'+hit.origin_id).then(o=>go(objectScreen(o))).catch(e=>setError(e.message))}>定位来源关系</button>}</div></article>)}</section>:null})}</>}
 </section></RootPortal>;
}
