"use client";
import {finalReceipts} from '../../core/result-output';
import {ModuleStatus} from '../../core/module-status';
import {ProjectBoard} from './project-board';
import {useState} from 'react';
import {useRuntime,entityRef} from '../../core/runtime-context';
import {Action,Field} from '../../core/runtime-panels';
import {type Entity,text,statuses} from '../live/types';
import type {Screen} from '../../core/screen';
export function ProjectWork({project,go,onBack}:{project:Entity;go:(screen:Screen)=>void;onBack:()=>void}){
 const r=useRuntime()!,s=r.snapshot!,owner=project.owner===s.user.id,[limit,setLimit]=useState(String((project.data.public_budget as {limit?:number})?.limit||3000)),[goal,setGoal]=useState(''),[reason,setReason]=useState('');
 const stages=(s.objects.project_stage||[]).filter(x=>x.space===project.id);
 return <section className="v277-edit-card"><h3>共创过程</h3><ProjectBoard project={project}/><p>{project.data.status==='ended'?'项目已结束':'各成员在本人的副本中工作，审查后共享阶段成果。共享不等于提交或公开发布。'}</p>{Boolean(project.data.origin_release)&&<button onClick={()=>go({name:'knowledge-detail',id:text(project,'origin_release')})}>查看原作与署名</button>}<ModuleStatus types={['project_stage']}>{stages.map(stage=><details key={stage.id}><summary>{text(stage,'title')}{stage.data.status==='superseded'?'（已有更新，保留历史）':''} · {project.members?.find(m=>m.id===stage.owner)?.name} · 阶段版本 {stage.version}</summary><p style={{whiteSpace:'pre-wrap'}}>{text(stage,'content')}</p><p>共享时间：{new Date(stage.created).toLocaleString('zh-CN')}</p></details>)}</ModuleStatus><h4>公共调度额度</h4><p>已使用 {Number(project.data.public_budget_used||0)} / {Number((project.data.public_budget as {limit?:number})?.limit||0)}。公共调度由发起者本人承担；成员工作使用各自额度。</p>{owner&&project.data.status==='active'&&<><Field name="本项目公共额度上限" type="number" value={limit} onChange={setLimit}/><Action run={()=>r.command('project.budget',{...entityRef(project),limit:Number(limit),confirm:true})}>确认使用本人额度</Action><Field name="本次需要协调的事项" area value={goal} onChange={setGoal}/><Action disabled={!goal.trim()||!project.data.public_budget} run={async()=>{const result=await r.command('project.dispatch',{id:project.id,goal,confirm:true,model_consent:true});go({name:'task',id:result.id})}}>准备临时调度任务，核对后启动</Action></>}{project.data.status==='active'&&<details><summary>{owner?'结束项目':'退出项目'}</summary><p>{owner?'停止招募与新执行，保留既有成果和历史。':'停止本人执行及后续读取，不代你提交未完成的副本。'}</p><Field name="说明" value={reason} onChange={setReason}/><Action run={async()=>{await r.command(owner?'project.end':'project.leave',{...entityRef(project),confirm:true,reason});if(!owner)onBack()}}>确认{owner?'结束':'退出'}</Action></details>}</section>;
}
export function CopyWork({copy,go}:{copy:Entity;go:(screen:Screen)=>void}){
 const r=useRuntime()!,s=r.snapshot!,[goal,setGoal]=useState(''),[title,setTitle]=useState(''),[reviewed,setReviewed]=useState(false),[system,setSystem]=useState('create');
 const task=s.objects.task.find(t=>t.id===copy.data.ai_task_id),run=s.objects.run.find(t=>t.id===task?.data.run_id),output=finalReceipts((run?.data.receipts||[]) as {output?:unknown;phase?:string}[]).find(x=>typeof x.output==='string')?.output;
 const stages=(s.objects.project_stage||[]).filter(x=>x.space===copy.data.project_id&&x.data.status==='shared');
 return <details><summary>用本人 AI 协作、共享阶段成果与文件</summary><p>AI 只在本人任务中生成结果，必须由本人检查并写入副本，随后仍需单独提交和发布。</p><Field name="本次希望完成的工作" area value={goal} onChange={setGoal}/><label className="v277-field">负责 Agent<select value={system} onChange={e=>setSystem(e.target.value)}>{s.systems.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><Action disabled={copy.data.status!=='draft'||!goal.trim()} run={async()=>{const result=await r.command('copy.ai_prepare',{...entityRef(copy),goal,system,confirm:true,model_consent:true});go({name:'task',id:result.id})}}>准备本人 AI 工作任务，核对后启动</Action>{task&&<p>{statuses[text(task,'status')]} <button onClick={()=>go({name:'task',id:task.id})}>查看工作结果</button></p>}{typeof output==='string'&&<><p style={{whiteSpace:'pre-wrap'}}>{output}</p><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>已核对结果与副本，确认替换正文</label><Action disabled={!reviewed||copy.data.status!=='draft'} run={()=>r.command('copy.ai_apply',{...entityRef(copy),reviewed:true})}>写入本人副本，暂不提交</Action></>}
 <h4>引用共享阶段版本</h4>{stages.map(stage=><div key={stage.id}><p>{text(stage,'title')} · {stage.version}</p><Action disabled={copy.data.status!=='draft'} run={()=>r.command('stage.depend',{...entityRef(copy),stage_id:stage.id})}>将此版本作为工作依据</Action></div>)}<h4>共享本人已保存的阶段内容</h4><Field name="阶段标题" value={title} onChange={setTitle}/><p>共享范围为当前项目成员，先核对正文不含未授权的私人资料；这不会正式提交贡献。</p><Action disabled={copy.data.status!=='draft'||!title.trim()||!text(copy,'content').trim()} run={()=>r.command('copy.stage',{...entityRef(copy),title,reviewed:true})}>已审查，确认共享当前保存版</Action><FilesEditor copy={copy}/>{Boolean((copy.data.unresolved_conflicts as string[]|undefined)?.length)&&<section><p role="alert">待解决冲突：{(copy.data.unresolved_conflicts as string[]).join("、")}。请对照上游修改文件，保存后再确认。</p><Action run={()=>r.command('copy.resolve',{...entityRef(copy),reviewed:true})}>已逐文件核对，确认保留当前保存内容</Action></section>}</details>;
}
function FilesEditor({copy}:{copy:Entity}){
 const r=useRuntime()!,[base,setBase]=useState(copy.version),[files,setFiles]=useState<Record<string,string>>(copy.data.files as Record<string,string>||{}),[path,setPath]=useState('');
 const stale=base!==copy.version;
 return <details><summary>项目文件 · {Object.keys(files).length} 个</summary><p>文本文件保留版本，采纳时逐文件合并；同一文件冲突不会覆盖上游修改。</p>{stale&&<button onClick={()=>{setFiles(copy.data.files as Record<string,string>||{});setBase(copy.version)}}>载入最新文件后编辑</button>}{Object.entries(files).map(([name,content])=><details key={name}><summary>{name}</summary><Field name={name} area value={content} onChange={value=>setFiles(old=>({...old,[name]:value}))}/><button onClick={()=>setFiles(old=>Object.fromEntries(Object.entries(old).filter(([key])=>key!==name)))}>移除此文件</button></details>)}<Field name="新增文件路径，如 notes/说明.md" value={path} onChange={setPath}/><button disabled={!path.trim()||path in files} onClick={()=>{setFiles(old=>({...old,[path]:''}));setPath('')}}>添加文件</button><Action disabled={stale||copy.data.status!=='draft'} run={async()=>{await r.command('copy.files',{...entityRef(copy),files});const current=await r.request<Entity>('/objects/'+copy.id);setBase(current.version);setFiles(current.data.files as Record<string,string>||{})}}>保存文件修改</Action></details>;
}
