"use client";
import {useEffect,useState} from 'react';
import {useRuntime} from '../../core/runtime-context';
import {Action} from '../../core/runtime-panels';
import {text,statuses} from '../live/types';
import type {Screen} from '../../core/screen';
export type SearchHit={id:string;version:number;type:string;title:string;excerpt:string;anchor:string;origin_id?:string;condition_status:string;condition_checks:{condition:string;status:string;evidence:string}[]};
export type SemanticResult={hits:SearchHit[];coverage:{processed_chunks:number;accumulated_chunks:number;batch_chunks:number;total_chunks:number;offset:number;next_offset:number|null;status:string}};
type Scope={plan_key:string|null;status:string;chunks:{id:string;title:string;anchor:string;version:number;characters:number}[];total_chunks:number;offset:number;next_offset:number|null;max_calls:number;max_units:number;max_tokens:number};
export function SemanticSearch({input,onResults,go}:{input:Record<string,unknown>;onResults:(result:SemanticResult,id:string)=>void;go:(screen:Screen)=>void}){
 const runtime=useRuntime()!,[scope,setScope]=useState<Scope|null>(null),[taskId,setTaskId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[coverage,setCoverage]=useState<SemanticResult['coverage']|null>(null),key=JSON.stringify(input);
 const task=runtime.snapshot!.objects.task.find(t=>t.id===taskId),run=runtime.snapshot!.objects.run.find(r=>r.id===task?.data.run_id);
 const load=async(offset=0)=>{setBusy(true);setError('');try{setScope(await runtime.request<Scope>('/search-scope',{...input,semantic_offset:offset}));}catch(e){setError(e instanceof Error?e.message:'范围读取失败')}finally{setBusy(false)}};
 useEffect(()=>{if(!taskId||!run||!['completed','awaiting_review','partial','blocked','failed','reconciliation_required'].includes(text(run,'status')))return;let active=true;void runtime.request<SemanticResult>('/search-semantic',{...JSON.parse(key),semantic_task_id:taskId}).then(result=>{if(active){setCoverage(result.coverage);onResults(result,taskId)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[taskId,run?.version,key]);
 return <details><summary>按含义查找更多资料{runtime.snapshot!.provider.embedding==='configured'?'':' · 服务未配置'}</summary><p>可找回没有共同关键词的相关文字，再与基础结果合并排序。相似度不代表条件已核实。每批最多 40 个文字片段；未搜索的范围会保留提示。</p><button disabled={busy} onClick={()=>void load()}>查看本次可读范围与额度</button>{error&&<p role="alert">{error}。基础结果仍可使用。</p>}{scope&&<><p>本次片段 {scope.offset+1}—{scope.offset+scope.chunks.length}，当前范围共 {scope.total_chunks} 个片段。最多 {scope.max_calls} 次请求、{scope.max_units} 本地额度，文本用量上限 {scope.max_tokens}。实际供应商用量记入任务。</p><details><summary>本次会交给向量服务的资料</summary>{scope.chunks.map((c,i)=><p key={c.id+':'+i}>{c.title} · v{c.version} · {c.anchor} · {c.characters} 字</p>)}</details><Action disabled={!scope.plan_key||!scope.chunks.length||['queued','running'].includes(text(task,'status'))} run={async()=>{setError('');const result=await runtime.command('search.semantic',{...input,semantic_offset:scope.offset,semantic_previous_id:scope.offset?taskId:undefined,plan_key:scope.plan_key,confirm:true,model_consent:true});setTaskId(result.id);setCoverage(null)}}>确认此范围，开始语义检索</Action></>}{task&&<p>{statuses[text(task,'status')]||text(task,'status')} <button onClick={()=>go({name:'task',id:task.id})}>查看运行、停止或恢复</button></p>}{coverage&&<p>本次已完成 {coverage.processed_chunks}/{coverage.batch_chunks} 个片段，累计已查 {coverage.accumulated_chunks}/{coverage.total_chunks} 个片段{coverage.status==='partial'?'；未完成部分保留在任务中，可恢复':''}。{coverage.status==='complete'&&coverage.next_offset!==null&&<button disabled={busy} onClick={()=>void load(coverage.next_offset!)}>查看下一批范围（{coverage.total_chunks-coverage.next_offset} 个片段待查）</button>}</p>}</details>;
}
