"use client";
import {useState} from 'react';
import {ExternalResults} from './external-tools';
import {TaskCollaboration} from './task-collaboration';
import {useRuntime,entityRef} from '../../core/runtime-context';
import {Action,Field} from '../../core/runtime-panels';
import {text,type Entity} from '../live/types';
const fieldLabels:Record<string,string>={title:'标题',summary:'摘要',content:'正文',text:'文字',goal:'目标'};
const labels:Record<string,string>={owner:'Person · 本人全局',explore:'探索',advise:'参谋',create:'创作',connect:'连接',execute:'执行'};
export function TaskContext({task}:{task:Entity}){
 const runtime=useRuntime()!,s=runtime.snapshot!,[holder,setHolder]=useState('owner'),[purpose,setPurpose]=useState(''),[hours,setHours]=useState('24'),[fields,setFields]=useState<string[]>(['summary']),[target,setTarget]=useState(text(task,'system')),[reason,setReason]=useState('');
 const suggestion=task.data.routing_suggestion as {system:string;reason:string;collaborators:string[]}|null;
 const requests=s.objects.context_request.filter(r=>r.data.task_id===task.id);
 return <section className="v277-edit-card"><ExternalResults task={task}/><h3>主责与本次资料范围</h3><p>主责：{labels[text(task,'system')]}。按最终成果分工：找资料交探索，比较决策交参谋，制作成果交创作，沟通协作交连接，推进落地交执行。</p>{Boolean(task.data.parameter_values)&&Object.keys(task.data.parameter_values as Record<string,string>).length>0&&<details><summary>本次工具输入</summary>{Object.entries(task.data.parameter_values as Record<string,string>).map(([name,value])=><p key={name}><b>{name}：</b>{value}</p>)}</details>}{task.data.status==='draft'&&<>{suggestion&&<aside><p>{suggestion.reason}</p>{suggestion.system!==task.data.system&&!task.data.media_operation&&<Action run={()=>runtime.command('task.route',{...entityRef(task),system:suggestion.system,reason:suggestion.reason,confirm:true})}>确认转交{labels[suggestion.system]}</Action>}{suggestion.collaborators.length>0&&<p>目标还提到了{suggestion.collaborators.map(s=>labels[s]).join('、')}的工作；可在下方协作方案中核对是否需要参与。本次未自动增加调用。</p>}</aside>}<details><summary>调整主责系统</summary><select aria-label="新的主责系统" value={target} onChange={e=>setTarget(e.target.value)}>{Object.entries(labels).filter(([id])=>id!=='owner').map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><Field name="转交原因与最终成果" value={reason} onChange={setReason}/><Action disabled={!reason.trim()||target===task.data.system} run={()=>runtime.command('task.route',{...entityRef(task),system:target,reason,confirm:true})}>确认转交同一任务</Action></details><details><summary>按需申请其他系统的资料</summary><label className="v277-field">资料归属<select value={holder} onChange={e=>setHolder(e.target.value)}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><Field name="本次用途与需要解决的问题" value={purpose} onChange={setPurpose}/><p>只申请需要的字段：</p>{[['title','标题'],['summary','摘要'],['content','正文'],['text','文字'],['goal','目标']].map(([id,name])=><label key={id}><input type="checkbox" checked={fields.includes(id)} onChange={e=>setFields(old=>e.target.checked?[...old,id]:old.filter(f=>f!==id))}/>{name} </label>)}<Field name="有效时长（小时，最多 720）" type="number" value={hours} onChange={setHours}/><p>仅供此任务使用，不对外共享；提出请求不等于已经获准。</p><Action disabled={!purpose.trim()||!fields.length||!Number.isFinite(Number(hours))||Number(hours)<=0||Number(hours)>720} run={async()=>{await runtime.command('context.request',{task_id:task.id,task_version:task.version,holder,purpose,fields,expires:new Date(Date.now()+Number(hours)*3600000).toISOString()});setPurpose('')}}>保存资料请求，核对后授权</Action></details></>}{task.data.mode==='compose'&&!task.data.media_operation&&<TaskCollaboration key={task.id+':'+task.data.system} task={task}/>} {requests.map(r=><ContextResponse key={r.id} request={r}/>)}{((task.data.routing_history||[]) as {from:string;to:string;reason:string}[]).map((r,i)=><p key={i}>{labels[r.from]} → {labels[r.to]}：{r.reason}</p>)}</section>;
}
function ContextResponse({request}:{request:Entity}){
 const runtime=useRuntime()!,s=runtime.snapshot!,[selected,setSelected]=useState<{id:string;version:number}[]>([]),[note,setNote]=useState(''),[fields,setFields]=useState(request.data.fields as string[]);
 const resources=[...s.objects.memory.filter(m=>m.data.scope===request.data.holder),...s.objects.knowledge,...s.objects.document,...s.objects.resource],stale=selected.some(ref=>!resources.some(r=>r.id===ref.id&&r.version===ref.version)),expired=Number(request.data.expires)<=Date.parse(s.server_time);
 const recovery=request.data.recovery_task as {id:string;version:number;status:string;source_invalid?:boolean}|null;
 const names:Record<string,string>={pending:'待本人核对',fulfilled:'已提供',partial:'部分满足',denied:'已拒绝',needs_input:'需补充，可另提请求',revoked:'已撤销'};
 return <article><b>{labels[text(request,'holder')]} → {labels[text(request,'requester')]} · {names[text(request,'status')]||text(request,'status')}</b><p>{text(request,'purpose')}</p><small>{expired?'已到期':'有效至 '+new Date(Number(request.data.expires)).toLocaleString('zh-CN')} · 仅此任务使用</small>{request.data.status==='pending'&&!expired&&<details><summary>核对、部分提供或拒绝</summary><p>仅提供勾选字段；未选择的资料不会传给执行任务。</p>{(request.data.fields as string[]).map(f=><label key={f}><input type="checkbox" checked={fields.includes(f)} onChange={e=>setFields(old=>e.target.checked?[...old,f]:old.filter(x=>x!==f))}/>{fieldLabels[f]} </label>)}{resources.map(o=><label key={o.id} style={{display:'block'}}><input type="checkbox" checked={selected.some(r=>r.id===o.id)} disabled={!selected.some(r=>r.id===o.id)&&selected.length>=10} onChange={e=>setSelected(old=>e.target.checked?[...old,entityRef(o)]:old.filter(r=>r.id!==o.id))}/>{text(o,'title')||text(o,'content').slice(0,80)} · v{o.version}</label>)}{selected.map(ref=>{const o=resources.find(r=>r.id===ref.id&&r.version===ref.version);return o?<pre key={ref.id} style={{whiteSpace:'pre-wrap'}}>{fields.map(f=>`${fieldLabels[f]}：${String(o.data[f]??'（此资料没有该字段）')}`).join('\n')}</pre>:<p key={ref.id} role="alert">所选资料已变化，请取消旧选择。</p>})}<Field name="提供范围、缺口或拒绝原因" value={note} onChange={setNote} area/>{[['fulfill','确认提供所选字段'],['partial','仅提供部分资料'],['deny','拒绝此请求'],['supplement','要求补充说明']].map(([decision,label])=><Action key={decision} disabled={!note.trim()||(['fulfill','partial'].includes(decision)&&(!selected.length||!fields.length||stale))} run={()=>runtime.command('context.respond',{...entityRef(request),decision,note,source_refs:selected,fields,confirm:true})}>{label}</Action>)}</details>}{recovery&&['ready','blocked','failed','partial','paused','cancelled'].includes(recovery.status)&&(expired||request.data.status==='revoked'||recovery.source_invalid)&&<details><summary>为原任务重新选择资料</summary><p>清空原资料和协作选择，撤销旧授权，保留任务目标、历史结果与累计用量。重新选择并确认后才能启动。</p><Action run={()=>runtime.command('task.reopen_context',{id:recovery.id,version:recovery.version,confirm:true})}>确认恢复成待核对的任务草稿</Action></details>}{text(request,'note')&&<p>{text(request,'note')}</p>}{!['revoked','denied'].includes(text(request,'status'))&&<Action run={()=>runtime.command('context.revoke',entityRef(request))}>撤销此资料请求与授权</Action>}</article>;
}
